"""
pages/02_Portfolio.py
=====================

Institutional Scanner Monitor

Portfolio Dashboard

Displays the latest portfolio reports
generated by the workflow.
"""

from __future__ import annotations

from dataclasses import dataclass

import pandas as pd
import plotly.express as px
import streamlit as st

from core.logger import get_logger
from core.session import initialize as initialize_session
from core.theme import (
    apply_theme,
    inject_card_css,
)

from ui.cards import (
    divider,
    empty_state,
    section,
)

from ui.loader import (
    ReportData,
    load_reports,
)

from ui.metrics import (
    dataframe_info,
    portfolio_kpis,
)

from ui.sidebar import (
    render_sidebar,
)

from ui.tables import (
    holdings_table,
    portfolio_table,
)

LOGGER = get_logger(__name__)

# =============================================================================
# Configuration
# =============================================================================


@dataclass(slots=True, frozen=True)
class PortfolioConfig:
    """
    Portfolio page configuration.
    """

    page_title: str = "Portfolio"

    page_icon: str = "💼"

    layout: str = "wide"

    preview_rows: int = 20

    chart_height: int = 420

    top_holdings: int = 10


CONFIG = PortfolioConfig()

# =============================================================================
# Streamlit Configuration
# =============================================================================

st.set_page_config(
    page_title=CONFIG.page_title,
    page_icon=CONFIG.page_icon,
    layout=CONFIG.layout,
)

apply_theme()

inject_card_css()

render_sidebar()

initialize_session()

# =============================================================================
# Report Loading
# =============================================================================


@st.cache_data(show_spinner=False)
def get_reports() -> ReportData:
    """
    Load generated workflow reports.
    """

    return load_reports()


try:

    reports = get_reports()

    latest = reports.latest

    history = reports.history

except Exception:

    LOGGER.exception(
        "Unable to load portfolio reports."
    )

    st.error(
        "Unable to load portfolio reports."
    )

    st.stop()

# =============================================================================
# Validation
# =============================================================================


def validate_reports(
    reports: ReportData,
) -> bool:
    """
    Validate required reports.
    """

    required_reports = {

        "Portfolio Summary":

            latest.get(
                "portfolio_summary",
                pd.DataFrame(),
            ),


        "Holdings":

            latest.get(
                "holdings",
                pd.DataFrame(),
            ),

    }

    missing = [

        report

        for report, dataframe

        in required_reports.items()

        if dataframe.empty

    ]

    if not missing:

        return True

    empty_state(

        "Portfolio Reports Missing",

        (
            "The following reports "
            "are unavailable:\n\n"

            + "\n".join(
                f"• {item}"
                for item in missing
            )

            + "\n\nRun the workflow "
              "to regenerate reports."

        ),

    )

    return False


if not validate_reports(
    reports,
):

    st.stop()

# =============================================================================
# Working Reports
# =============================================================================

portfolio_summary = latest.get(

    "portfolio_summary",

    pd.DataFrame(),

)


holdings = latest.get(

    "holdings",

    pd.DataFrame(),

)


risk_summary = latest.get(

    "risk_summary",

    pd.DataFrame(),

)


execution_summary = latest.get(

    "execution_summary",

    pd.DataFrame(),

)


portfolio_history = history.get(

    "portfolio_history",

    pd.DataFrame(),

)

# =============================================================================
# Page Header
# =============================================================================

section(

    "Portfolio Dashboard",

    (
        "Overview of the latest "
        "workflow-generated "
        "portfolio reports."
    ),

)

portfolio_kpis(
    portfolio_summary,
)

divider()

# =============================================================================
# Portfolio Summary
# =============================================================================

section(

    "Portfolio Summary",

    (
        "Latest portfolio "
        "summary report."
    ),

)

portfolio_table(
    portfolio_summary,
)

dataframe_info(
    portfolio_summary,
)

divider()

# =============================================================================
# Holdings
# =============================================================================

section(

    "Current Holdings",

    (
        "Current portfolio "
        "positions."
    ),

)

holdings_table(

    holdings,

    key="portfolio_holdings",

)

dataframe_info(
    holdings,
)

divider()

# =============================================================================
# Sector Allocation
# =============================================================================

section(
    "Sector Allocation",
    (
        "Portfolio allocation by sector "
        "from the latest holdings report."
    ),
)

if (
    not holdings.empty
    and "Sector" in holdings.columns
):

    sector_summary = (

        holdings

        .groupby(
            "Sector",
            dropna=False,
        )

        .size()

        .reset_index(
            name="Holdings",
        )

        .sort_values(
            "Holdings",
            ascending=False,
        )

    )

    chart_col, table_col = st.columns(
        [2, 1],
    )

    with chart_col:

        figure = px.pie(

            sector_summary,

            names="Sector",

            values="Holdings",

            hole=0.45,

            title="Sector Allocation",

        )

        figure.update_traces(

            textposition="inside",

            textinfo="percent+label",

        )

        st.plotly_chart(

            figure,

            use_container_width=True,

        )

    with table_col:

        st.dataframe(

            sector_summary,

            use_container_width=True,

            hide_index=True,

            height=CONFIG.chart_height,

        )

else:

    st.info(
        "Sector information "
        "is not available."
    )

divider()

# =============================================================================
# Top Holdings
# =============================================================================

section(
    "Top Holdings",
    (
        "Largest holdings from the "
        "latest portfolio report."
    ),
)

sort_column = None

for column in (

    "Portfolio Weight",

    "Weight",

    "Weight (%)",

    "Market Value",

    "Current Value",

):

    if column in holdings.columns:

        sort_column = column

        break

if (
    sort_column is not None
    and not holdings.empty
):

    top_holdings = (

        holdings

        .sort_values(

            sort_column,

            ascending=False,

        )

        .head(

            CONFIG.top_holdings,

        )

    )

    left, right = st.columns(
        [2, 1],
    )

    with left:

        holdings_table(

            top_holdings,

            key="top_holdings",

        )

    with right:

        symbol_column = None

        for column in (

            "Symbol",

            "Ticker",

            "Stock",

        ):

            if column in top_holdings.columns:

                symbol_column = column

                break

        if symbol_column:

            figure = px.bar(

                top_holdings,

                x=symbol_column,

                y=sort_column,

                text=sort_column,

                title="Largest Holdings",

            )

            figure.update_traces(

                textposition="outside",

            )

            figure.update_layout(

                xaxis_title=None,

                yaxis_title=sort_column,

            )

            st.plotly_chart(

                figure,

                use_container_width=True,

            )

else:

    st.info(
        "Top holdings are "
        "not available."
    )

divider()

# =============================================================================
# Portfolio Insights
# =============================================================================

section(
    "Portfolio Insights",
    (
        "Highlights from the latest "
        "portfolio reports."
    ),
)

insights: list[str] = []

# ---------------------------------------------------------
# Portfolio Summary
# ---------------------------------------------------------

if not portfolio_summary.empty:

    first_row = portfolio_summary.iloc[0]

    for column in (

        "Portfolio Health",

        "Overall Health",

        "Health Score",

    ):

        if column in portfolio_summary.columns:

            insights.append(

                f"Portfolio Health : "
                f"{first_row[column]}"

            )

            break

    for column in (

        "Portfolio Value",

        "Market Value",

        "Current Value",

    ):

        if column in portfolio_summary.columns:

            insights.append(

                f"Portfolio Value : "
                f"{first_row[column]}"

            )

            break

    for column in (

        "Total Return",

        "Portfolio Return",

        "Return",

    ):

        if column in portfolio_summary.columns:

            insights.append(

                f"Portfolio Return : "
                f"{first_row[column]}"

            )

            break

# ---------------------------------------------------------
# Risk Summary
# ---------------------------------------------------------

if not risk_summary.empty:

    risk_row = risk_summary.iloc[0]

    for column in (

        "Risk Level",

        "Overall Risk",

    ):

        if column in risk_summary.columns:

            insights.append(

                f"Risk Level : "
                f"{risk_row[column]}"

            )

            break

    for column in (

        "VaR 95%",

        "VaR",

    ):

        if column in risk_summary.columns:

            insights.append(

                f"VaR (95%) : "
                f"{risk_row[column]}"

            )

            break

# ---------------------------------------------------------
# Execution Summary
# ---------------------------------------------------------

if not execution_summary.empty:

    execution_row = execution_summary.iloc[0]

    for column in (

        "Orders",

        "Orders Executed",

        "Executed Orders",

    ):

        if column in execution_summary.columns:

            insights.append(

                f"Executed Orders : "
                f"{execution_row[column]}"

            )

            break

# ---------------------------------------------------------
# Display
# ---------------------------------------------------------

if insights:

    for insight in insights:

        st.success(
            insight,
            icon="📌",
        )

else:

    st.info(
        "No portfolio insights "
        "available."
    )

divider()

# =============================================================================
# Report Overview
# =============================================================================

section(
    "Report Overview",
    (
        "Generated workflow reports."
    ),
)

overview = pd.DataFrame(

    [

        {

            "Report": "Portfolio Summary",

            "Rows": len(
                portfolio_summary,
            ),

            "Status":

                "Available"

                if not portfolio_summary.empty

                else "Missing",

        },

        {

            "Report": "Holdings",

            "Rows": len(
                holdings,
            ),

            "Status":

                "Available"

                if not holdings.empty

                else "Missing",

        },

        {

            "Report": "Risk Summary",

            "Rows": len(
                risk_summary,
            ),

            "Status":

                "Available"

                if not risk_summary.empty

                else "Missing",

        },

        {

            "Report": "Execution Summary",

            "Rows": len(
                execution_summary,
            ),

            "Status":

                "Available"

                if not execution_summary.empty

                else "Missing",

        },

    ]

)

st.dataframe(

    overview,

    use_container_width=True,

    hide_index=True,

)

divider()

# =============================================================================
# Quick Navigation
# =============================================================================

section(
    "Explore Reports",
    (
        "Navigate using the left "
        "sidebar to view detailed "
        "analytics."
    ),
)

col1, col2 = st.columns(2)

with col1:

    st.info(
        """
📁 **Holdings**

View all portfolio holdings.
"""
    )

    st.info(
        """
📊 **Daily Monitor**

Latest scanner output.
"""
    )

    st.info(
        """
🛡️ **Risk**

Portfolio risk analytics.
"""
    )

with col2:

    st.info(
        """
📈 **Performance**

Performance reporting.
"""
    )

    st.info(
        """
⚙️ **Execution**

Execution summary.
"""
    )

    st.info(
        """
📥 **Downloads**

Export workflow reports.
"""
    )

divider()

# =============================================================================
# Footer
# =============================================================================

st.caption(
    "Institutional Scanner Monitor"
)

st.caption(
    "Portfolio Dashboard • "
    "Workflow Report Viewer"
)