"""
pages/03_Holdings.py
====================

Institutional Scanner Monitor

Holdings Dashboard

Displays the latest portfolio holdings
generated by the workflow.
"""

from __future__ import annotations

from dataclasses import dataclass

import pandas as pd
import plotly.express as px
import streamlit as st

from core.logger import get_logger
from core.session import (
    initialize as initialize_session,
)
from core.theme import (
    apply_theme,
    inject_card_css,
)

from ui.cards import (
    divider,
    empty_state,
    section,
)

from ui.loader import (
    ReportData,
    load_reports,
)

from ui.metrics import (
    dataframe_info,
    holdings_kpis,
)

from ui.sidebar import (
    render_sidebar,
)

from ui.tables import (
    holdings_table,
)

LOGGER = get_logger(__name__)

# =============================================================================
# Configuration
# =============================================================================


@dataclass(slots=True, frozen=True)
class HoldingsConfig:
    """
    Holdings page configuration.
    """

    page_title: str = "Holdings"

    page_icon: str = "💼"

    layout: str = "wide"

    preview_rows: int = 25

    table_height: int = 650

    chart_height: int = 420

    top_holdings: int = 10


CONFIG = HoldingsConfig()

# =============================================================================
# Streamlit Configuration
# =============================================================================

st.set_page_config(
    page_title=CONFIG.page_title,
    page_icon=CONFIG.page_icon,
    layout=CONFIG.layout,
)

apply_theme()

inject_card_css()

render_sidebar()

initialize_session()

# =============================================================================
# Report Loading
# =============================================================================


@st.cache_data(show_spinner=False)
def get_reports() -> ReportData:
    """
    Load workflow reports.
    """

    return load_reports()


try:

    reports = get_reports()

    latest = reports.latest

    history = reports.history

except Exception:

    LOGGER.exception(
        "Unable to load holdings reports."
    )

    st.error(
        "Unable to load holdings reports."
    )

    st.stop()

# =============================================================================
# Validation
# =============================================================================


def validate_reports(
    reports: ReportData,
) -> bool:
    """
    Validate required reports.
    """

    required_reports = {

        "Holdings":
            latest.get(
                "holdings",
                pd.DataFrame(),
            ),
    }

    missing = [

        report

        for report, dataframe

        in required_reports.items()

        if dataframe.empty

    ]

    if not missing:

        return True

    empty_state(

        "Holdings Report Missing",

        (
            "The following report "
            "is unavailable:\n\n"

            + "\n".join(
                f"• {report}"
                for report in missing
            )

            + "\n\nRun the workflow "
              "to regenerate reports."

        ),

    )

    return False


if not validate_reports(
    reports,
):

    st.stop()

# =============================================================================
# Working Reports
# =============================================================================

holdings = latest.get(

    "holdings",

    pd.DataFrame(),

)


portfolio_summary = latest.get(

    "portfolio_summary",

    pd.DataFrame(),

)


risk_summary = latest.get(

    "risk_summary",

    pd.DataFrame(),

)

# =============================================================================
# Page Header
# =============================================================================

section(
    "Holdings Dashboard",
    (
        "View and explore the latest "
        "portfolio holdings generated "
        "by the workflow."
    ),
)

holdings_kpis(
    holdings,
)

divider()

# =============================================================================
# Holdings Filters
# =============================================================================

section(
    "Holdings Filters",
    (
        "Filter portfolio positions "
        "by symbol and sector."
    ),
)

filter_col1, filter_col2 = st.columns(2)

with filter_col1:

    search_symbol = st.text_input(
        "Search Symbol",
        placeholder="RELIANCE",
    )

with filter_col2:

    if "Sector" in holdings.columns:

        sectors = [

            "All",

            *sorted(

                holdings["Sector"]

                .dropna()

                .astype(str)

                .unique()

                .tolist()

            ),

        ]

    else:

        sectors = ["All"]

    selected_sector = st.selectbox(
        "Sector",
        sectors,
    )

filtered_holdings = holdings.copy()

if search_symbol:

    symbol_column = None

    for column in (

        "Symbol",

        "Ticker",

        "Stock",

    ):

        if column in filtered_holdings.columns:

            symbol_column = column

            break

    if symbol_column is not None:

        filtered_holdings = (

            filtered_holdings[

                filtered_holdings[
                    symbol_column
                ]

                .astype(str)

                .str.contains(

                    search_symbol,

                    case=False,

                    na=False,

                )

            ]

        )

if (
    selected_sector != "All"
    and "Sector" in filtered_holdings.columns
):

    filtered_holdings = (

        filtered_holdings[

            filtered_holdings[
                "Sector"
            ]

            ==

            selected_sector

        ]

    )

divider()

# =============================================================================
# Current Holdings
# =============================================================================

section(
    "Current Holdings",
    (
        "Current portfolio positions "
        "from the latest workflow."
    ),
)

if filtered_holdings.empty:

    st.info(
        "No holdings match the "
        "selected filters."
    )

else:

    dataframe_info(
        filtered_holdings,
    )

    holdings_table(
        filtered_holdings,
        key="portfolio_holdings",
    )

divider()

# =============================================================================
# Sector Allocation
# =============================================================================

section(
    "Sector Allocation",
    (
        "Portfolio exposure by sector."
    ),
)

if (
    not filtered_holdings.empty
    and "Sector" in filtered_holdings.columns
):

    sector_summary = (

        filtered_holdings

        .groupby(
            "Sector",
            dropna=False,
        )

        .size()

        .reset_index(
            name="Holdings",
        )

        .sort_values(
            "Holdings",
            ascending=False,
        )

    )

    chart_col, table_col = st.columns(
        [2, 1],
    )

    with chart_col:

        figure = px.pie(

            sector_summary,

            names="Sector",

            values="Holdings",

            hole=0.45,

            title="Sector Allocation",

        )

        figure.update_traces(

            textposition="inside",

            textinfo="percent+label",

        )

        st.plotly_chart(

            figure,

            use_container_width=True,

        )

    with table_col:

        st.dataframe(

            sector_summary,

            use_container_width=True,

            hide_index=True,

            height=CONFIG.chart_height,

        )

else:

    st.info(
        "Sector information "
        "is unavailable."
    )

divider()

# =============================================================================
# Top Holdings
# =============================================================================

section(
    "Top Holdings",
    (
        "Largest portfolio positions."
    ),
)

weight_column = None

for column in (

    "Portfolio Weight",

    "Weight",

    "Weight (%)",

    "Market Value",

    "Current Value",

):

    if column in filtered_holdings.columns:

        weight_column = column

        break

symbol_column = None

for column in (

    "Symbol",

    "Ticker",

    "Stock",

):

    if column in filtered_holdings.columns:

        symbol_column = column

        break

if (

    symbol_column is not None

    and

    weight_column is not None

):

    top_holdings = (

        filtered_holdings

        .sort_values(

            weight_column,

            ascending=False,

        )

        .head(

            CONFIG.top_holdings,

        )

    )

    left, right = st.columns(
        [2, 1],
    )

    with left:

        holdings_table(

            top_holdings,

            key="top_holdings",

        )

    with right:

        figure = px.bar(

            top_holdings,

            x=symbol_column,

            y=weight_column,

            text=weight_column,

            title="Largest Holdings",

        )

        figure.update_traces(

            textposition="outside",

        )

        figure.update_layout(

            xaxis_title=None,

            yaxis_title=weight_column,

        )

        st.plotly_chart(

            figure,

            use_container_width=True,

        )

else:

    st.info(
        "Top holdings are "
        "not available."
    )

divider()

# =============================================================================
# Holding Detail
# =============================================================================

section(
    "Holding Detail",
    (
        "Inspect an individual "
        "portfolio position."
    ),
)

if (

    symbol_column is not None

    and

    not filtered_holdings.empty

):

    selected_symbol = st.selectbox(

        "Select Holding",

        sorted(

            filtered_holdings[
                symbol_column
            ]

            .dropna()

            .astype(str)

            .unique()

        ),

    )

    selected = filtered_holdings[

        filtered_holdings[
            symbol_column
        ]

        ==

        selected_symbol

    ]

    st.dataframe(

        selected,

        use_container_width=True,

        hide_index=True,

    )

else:

    st.info(
        "Holding details "
        "are unavailable."
    )

divider()

# =============================================================================
# Portfolio Insights
# =============================================================================

section(
    "Portfolio Insights",
    (
        "Key observations from the "
        "latest workflow reports."
    ),
)

insights: list[str] = []

# -------------------------------------------------------------------------
# Portfolio Summary
# -------------------------------------------------------------------------

if not portfolio_summary.empty:

    summary = portfolio_summary.iloc[0]

    for column in (

        "Portfolio Health",

        "Health Score",

        "Overall Health",

    ):

        if column in portfolio_summary.columns:

            insights.append(
                f"Portfolio Health : {summary[column]}"
            )

            break

    for column in (

        "Portfolio Value",

        "Market Value",

        "Current Value",

    ):

        if column in portfolio_summary.columns:

            insights.append(
                f"Portfolio Value : {summary[column]}"
            )

            break

    for column in (

        "Total Return",

        "Portfolio Return",

        "Return",

    ):

        if column in portfolio_summary.columns:

            insights.append(
                f"Portfolio Return : {summary[column]}"
            )

            break

# -------------------------------------------------------------------------
# Risk Summary
# -------------------------------------------------------------------------

if not risk_summary.empty:

    risk = risk_summary.iloc[0]

    for column in (

        "Risk Level",

        "Overall Risk",

    ):

        if column in risk_summary.columns:

            insights.append(
                f"Risk Level : {risk[column]}"
            )

            break

    for column in (

        "VaR 95%",

        "VaR",

    ):

        if column in risk_summary.columns:

            insights.append(
                f"VaR (95%) : {risk[column]}"
            )

            break

if insights:

    for insight in insights:

        st.success(
            insight,
            icon="💡",
        )

else:

    st.info(
        "Portfolio insights are "
        "not available."
    )

divider()

# =============================================================================
# Report Overview
# =============================================================================

section(
    "Report Overview",
    (
        "Summary of the reports "
        "used by this page."
    ),
)

overview = pd.DataFrame(

    [

        {

            "Report": "Portfolio Summary",

            "Rows": len(
                portfolio_summary,
            ),

            "Status":

                "Available"

                if not portfolio_summary.empty

                else "Missing",

        },

        {

            "Report": "Holdings",

            "Rows": len(
                holdings,
            ),

            "Status":

                "Available"

                if not holdings.empty

                else "Missing",

        },

        {

            "Report": "Risk Summary",

            "Rows": len(
                risk_summary,
            ),

            "Status":

                "Available"

                if not risk_summary.empty

                else "Missing",

        },

    ]

)

st.dataframe(

    overview,

    use_container_width=True,

    hide_index=True,

)

divider()

# =============================================================================
# Footer
# =============================================================================

st.caption(
    "Institutional Scanner Monitor"
)

st.caption(
    "Portfolio Holdings Dashboard"
)

st.caption(
    "Displaying the latest "
    "workflow-generated reports."
)