"""
pages/04_Daily_Monitor.py
=========================

Institutional Scanner Monitor

Daily Monitor Dashboard

Displays the latest scanner reports
generated by the workflow.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime

import pandas as pd
import plotly.express as px
import streamlit as st

from core.logger import get_logger
from core.session import (
    initialize as initialize_session,
)
from core.theme import (
    apply_theme,
    inject_card_css,
)

from ui.cards import (
    divider,
    empty_state,
    section,
)

from ui.loader import (
    ReportData,
    load_reports,
)

from ui.metrics import (
    dataframe_info,
    daily_monitor_kpis,
)

from ui.sidebar import (
    render_sidebar,
)

from ui.tables import (
    holdings_table,
)

LOGGER = get_logger(__name__)

# =============================================================================
# Configuration
# =============================================================================


@dataclass(slots=True, frozen=True)
class DailyMonitorConfig:
    """
    Daily Monitor configuration.
    """

    page_title: str = "Daily Monitor"

    page_icon: str = "📈"

    layout: str = "wide"

    preview_rows: int = 25

    table_height: int = 650

    chart_height: int = 420

    top_opportunities: int = 20


CONFIG = DailyMonitorConfig()

# =============================================================================
# Streamlit Configuration
# =============================================================================

st.set_page_config(
    page_title=CONFIG.page_title,
    page_icon=CONFIG.page_icon,
    layout=CONFIG.layout,
)

apply_theme()

inject_card_css()

render_sidebar()

initialize_session()

# =============================================================================
# Report Loading
# =============================================================================


@st.cache_data(show_spinner=False)
def get_reports() -> ReportData:
    """
    Load workflow reports.
    """

    return load_reports()


try:

    reports = get_reports()

    latest = reports.latest

    history = reports.history

except Exception:

    LOGGER.exception(
        "Unable to load daily monitor reports."
    )

    st.error(
        "Unable to load daily monitor reports."
    )

    st.stop()

# =============================================================================
# Validation
# =============================================================================


def validate_reports(
    reports: ReportData,
) -> bool:
    """
    Validate required reports.
    """

    required_reports = {

        "Daily Monitor":

            latest.get(
                "daily_monitor",
                pd.DataFrame(),
            ),

    }

    missing = [

        report

        for report, dataframe

        in required_reports.items()

        if dataframe.empty

    ]

    if not missing:

        return True

    empty_state(

        "Daily Monitor Report Missing",

        (
            "The following report "
            "is unavailable:\n\n"

            + "\n".join(
                f"• {report}"
                for report in missing
            )

            + "\n\nRun the workflow "
              "to regenerate reports."

        ),

    )

    return False


if not validate_reports(
    reports,
):

    st.stop()


# =============================================================================
# Working Reports
# =============================================================================

daily_monitor = latest.get(
    "daily_monitor",
    pd.DataFrame(),
)


portfolio_summary = latest.get(
    "portfolio_summary",
    pd.DataFrame(),
)


risk_summary = latest.get(
    "risk_summary",
    pd.DataFrame(),
)


execution_summary = latest.get(
    "execution_summary",
    pd.DataFrame(),
)


# =============================================================================
# Page Header
# =============================================================================

section(
    "Daily Monitor",
    (
        "Operational dashboard for "
        "the latest scanner output."
    ),
)

left, right = st.columns(
    [3, 1],
)

with left:

    st.caption(
        "Latest workflow-generated "
        "scanner report."
    )

with right:

    st.caption(
        datetime.now().strftime(
            "%d %b %Y %H:%M"
        )
    )

daily_monitor_kpis(
    daily_monitor=daily_monitor,
    portfolio_summary=portfolio_summary,
    risk_summary=risk_summary,
)

divider()

# =============================================================================
# Scanner Filters
# =============================================================================

section(
    "Scanner Filters",
    (
        "Filter the latest scanner "
        "report."
    ),
)

filter_col1, filter_col2 = st.columns(2)

with filter_col1:

    search_symbol = st.text_input(
        "Search Symbol",
        placeholder="RELIANCE",
    )

with filter_col2:

    if "Sector" in daily_monitor.columns:

        sectors = [

            "All",

            *sorted(

                daily_monitor["Sector"]

                .dropna()

                .astype(str)

                .unique()

                .tolist()

            ),

        ]

    else:

        sectors = ["All"]

    selected_sector = st.selectbox(
        "Sector",
        sectors,
    )

filtered_monitor = daily_monitor.copy()

symbol_column = None

for column in (

    "Symbol",

    "Ticker",

    "Stock",

):

    if column in filtered_monitor.columns:

        symbol_column = column

        break

if (

    symbol_column is not None

    and

    search_symbol

):

    filtered_monitor = (

        filtered_monitor[

            filtered_monitor[
                symbol_column
            ]

            .astype(str)

            .str.contains(

                search_symbol,

                case=False,

                na=False,

            )

        ]

    )

if (

    selected_sector != "All"

    and

    "Sector" in filtered_monitor.columns

):

    filtered_monitor = (

        filtered_monitor[

            filtered_monitor[
                "Sector"
            ]

            ==

            selected_sector

        ]

    )

divider()

# =============================================================================
# Live Scanner
# =============================================================================

section(
    "Live Scanner",
    (
        "Current scanner output "
        "from the latest workflow."
    ),
)

if filtered_monitor.empty:

    st.info(
        "No scanner records "
        "match the selected filters."
    )

else:

    dataframe_info(
        filtered_monitor,
    )

    holdings_table(

        filtered_monitor,

        key="daily_monitor",

    )

divider()

# =============================================================================
# Scanner Summary
# =============================================================================

section(
    "Scanner Summary",
    (
        "Summary of the loaded "
        "scanner report."
    ),
)

summary = pd.DataFrame(

    [

        {

            "Report": "Daily Monitor",

            "Rows": len(
                filtered_monitor,
            ),

            "Status":

                "Available"

                if not filtered_monitor.empty

                else "Empty",

        },

        {

            "Report": "Portfolio Summary",

            "Rows": len(
                portfolio_summary,
            ),

            "Status":

                "Available"

                if not portfolio_summary.empty

                else "Missing",

        },

        {

            "Report": "Risk Summary",

            "Rows": len(
                risk_summary,
            ),

            "Status":

                "Available"

                if not risk_summary.empty

                else "Missing",

        },

        {

            "Report": "Execution Summary",

            "Rows": len(
                execution_summary,
            ),

            "Status":

                "Available"

                if not execution_summary.empty

                else "Missing",

        },

    ]

)

st.dataframe(

    summary,

    use_container_width=True,

    hide_index=True,

)

divider()

# =============================================================================
# Top Opportunities
# =============================================================================

section(
    "Top Opportunities",
    (
        "Highest ranked opportunities "
        "from the latest scanner report."
    ),
)

score_column = None

for column in (

    "Score",

    "Composite Score",

    "Final Score",

    "Recommendation Score",

):

    if column in filtered_monitor.columns:

        score_column = column

        break

symbol_column = None

for column in (

    "Symbol",

    "Ticker",

    "Stock",

):

    if column in filtered_monitor.columns:

        symbol_column = column

        break

if (

    score_column is not None

    and

    symbol_column is not None

    and

    not filtered_monitor.empty

):

    top_opportunities = (

        filtered_monitor

        .sort_values(

            score_column,

            ascending=False,

        )

        .head(

            CONFIG.top_opportunities,

        )

    )

    chart_col, table_col = st.columns(
        [2, 1],
    )

    with chart_col:

        figure = px.bar(

            top_opportunities,

            x=symbol_column,

            y=score_column,

            text=score_column,

            title="Top Opportunities",

        )

        figure.update_traces(

            textposition="outside",

        )

        figure.update_layout(

            xaxis_title=None,

            yaxis_title=score_column,

        )

        st.plotly_chart(

            figure,

            use_container_width=True,

        )

    with table_col:

        st.dataframe(

            top_opportunities,

            use_container_width=True,

            hide_index=True,

            height=CONFIG.chart_height,

        )

else:

    st.info(
        "Opportunity data "
        "is unavailable."
    )

divider()

# =============================================================================
# Market Breadth
# =============================================================================

section(
    "Market Breadth",
    (
        "Distribution of scanner "
        "recommendations."
    ),
)

signal_column = None

for column in (

    "Signal",

    "Recommendation",

    "Action",

):

    if column in filtered_monitor.columns:

        signal_column = column

        break

if (

    signal_column is not None

    and

    not filtered_monitor.empty

):

    breadth = (

        filtered_monitor

        .groupby(
            signal_column,
            dropna=False,
        )

        .size()

        .reset_index(
            name="Count",
        )

        .sort_values(
            "Count",
            ascending=False,
        )

    )

    chart_col, table_col = st.columns(
        [2, 1],
    )

    with chart_col:

        figure = px.pie(

            breadth,

            names=signal_column,

            values="Count",

            hole=0.45,

            title="Signal Distribution",

        )

        figure.update_traces(

            textposition="inside",

            textinfo="percent+label",

        )

        st.plotly_chart(

            figure,

            use_container_width=True,

        )

    with table_col:

        st.dataframe(

            breadth,

            use_container_width=True,

            hide_index=True,

            height=CONFIG.chart_height,

        )

else:

    st.info(
        "Signal distribution "
        "is unavailable."
    )

divider()

# =============================================================================
# Opportunity Summary
# =============================================================================

section(
    "Opportunity Summary",
    (
        "Highest ranked records "
        "from today's scan."
    ),
)

if (

    score_column is not None

    and

    not filtered_monitor.empty

):

    st.dataframe(

        filtered_monitor

        .sort_values(

            score_column,

            ascending=False,

        )

        .head(10),

        use_container_width=True,

        hide_index=True,

    )

else:

    st.info(
        "No opportunity summary "
        "is available."
    )

divider()

# =============================================================================
# Daily Insights
# =============================================================================

section(
    "Daily Insights",
    (
        "Highlights from the latest "
        "workflow-generated scanner report."
    ),
)

insights: list[str] = []

# -------------------------------------------------------------------------
# Daily Monitor
# -------------------------------------------------------------------------

if not daily_monitor.empty:

    first_row = daily_monitor.iloc[0]

    for column in (

        "Market Regime",

        "Regime",

    ):

        if column in daily_monitor.columns:

            insights.append(
                f"Market Regime : {first_row[column]}"
            )

            break

    for column in (

        "Scan Date",

        "Date",

        "Trade Date",

    ):

        if column in daily_monitor.columns:

            insights.append(
                f"Latest Scan : {first_row[column]}"
            )

            break

# -------------------------------------------------------------------------
# Portfolio Summary
# -------------------------------------------------------------------------

if not portfolio_summary.empty:

    summary = portfolio_summary.iloc[0]

    for column in (

        "Portfolio Health",

        "Health Score",

        "Overall Health",

    ):

        if column in portfolio_summary.columns:

            insights.append(
                f"Portfolio Health : {summary[column]}"
            )

            break

# -------------------------------------------------------------------------
# Risk Summary
# -------------------------------------------------------------------------

if not risk_summary.empty:

    risk = risk_summary.iloc[0]

    for column in (

        "Risk Level",

        "Overall Risk",

    ):

        if column in risk_summary.columns:

            insights.append(
                f"Risk Level : {risk[column]}"
            )

            break

# -------------------------------------------------------------------------
# Display Insights
# -------------------------------------------------------------------------

if insights:

    for insight in insights:

        st.success(
            insight,
            icon="💡",
        )

else:

    st.info(
        "No workflow insights are "
        "currently available."
    )

divider()

# =============================================================================
# Report Status
# =============================================================================

section(
    "Report Status",
    (
        "Workflow reports used by "
        "this dashboard."
    ),
)

status = pd.DataFrame(

    [

        {

            "Report": "Daily Monitor",

            "Rows": len(
                daily_monitor,
            ),

            "Status":

                "Available"

                if not daily_monitor.empty

                else "Missing",

        },

        {

            "Report": "Portfolio Summary",

            "Rows": len(
                portfolio_summary,
            ),

            "Status":

                "Available"

                if not portfolio_summary.empty

                else "Missing",

        },

        {

            "Report": "Risk Summary",

            "Rows": len(
                risk_summary,
            ),

            "Status":

                "Available"

                if not risk_summary.empty

                else "Missing",

        },

        {

            "Report": "Execution Summary",

            "Rows": len(
                execution_summary,
            ),

            "Status":

                "Available"

                if not execution_summary.empty

                else "Missing",

        },

    ]

)

st.dataframe(

    status,

    use_container_width=True,

    hide_index=True,

)

divider()

# =============================================================================
# Quick Navigation
# =============================================================================

section(
    "Explore Reports",
    (
        "Navigate to other report "
        "pages using the sidebar."
    ),
)

col1, col2 = st.columns(2)

with col1:

    st.info(
        """
📁 **Portfolio**

Portfolio summary
and allocation.
"""
    )

    st.info(
        """
💼 **Holdings**

Current portfolio
positions.
"""
    )

    st.info(
        """
🛡️ **Risk**

Risk analytics
and exposure.
"""
    )

with col2:

    st.info(
        """
📈 **Performance**

Performance
reporting.
"""
    )

    st.info(
        """
⚙️ **Execution**

Execution
summary.
"""
    )

    st.info(
        """
📥 **Downloads**

Export generated
workflow reports.
"""
    )

divider()

# =============================================================================
# Footer
# =============================================================================

st.caption(
    "Institutional Scanner Monitor"
)

st.caption(
    "Daily Monitor Dashboard"
)

st.caption(
    "Workflow Report Viewer"
)