"""
pages/05_Risk.py
================

Institutional Scanner Monitor

Risk Dashboard

Displays workflow-generated
portfolio risk reports.
"""

from __future__ import annotations

from dataclasses import dataclass

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

from core.logger import get_logger
from core.session import (
    initialize as initialize_session,
)
from core.theme import (
    apply_theme,
    inject_card_css,
)

from ui.cards import (
    divider,
    empty_state,
    section,
)

from ui.loader import (
    ReportData,
    load_reports,
)

from ui.metrics import (
    dataframe_info,
    risk_kpis,
)

from ui.sidebar import (
    render_sidebar,
)

from ui.tables import (
    holdings_table,
)

LOGGER = get_logger(__name__)

# =============================================================================
# Configuration
# =============================================================================


@dataclass(slots=True, frozen=True)
class RiskConfig:
    """
    Risk dashboard configuration.
    """

    page_title: str = "Risk"

    page_icon: str = "⚠️"

    layout: str = "wide"

    chart_height: int = 420

    preview_rows: int = 20

    top_positions: int = 15


CONFIG = RiskConfig()

# =============================================================================
# Streamlit Configuration
# =============================================================================

st.set_page_config(

    page_title=CONFIG.page_title,

    page_icon=CONFIG.page_icon,

    layout=CONFIG.layout,

)

apply_theme()

inject_card_css()

render_sidebar()

initialize_session()

# =============================================================================
# Report Loading
# =============================================================================


@st.cache_data(show_spinner=False)
def get_reports() -> ReportData:
    """
    Load workflow reports.
    """

    return load_reports()


try:

    reports = get_reports()

    latest = reports.latest

    history = reports.history

except Exception:

    LOGGER.exception(
        "Unable to load risk reports."
    )

    st.error(
        "Unable to load risk reports."
    )

    st.stop()

# =============================================================================
# Validation
# =============================================================================


def validate_reports(
    reports: ReportData,
) -> bool:
    """
    Validate required reports.
    """

    required = {

        "Risk Summary":

            latest.get(
                "risk_summary",
                pd.DataFrame(),
            ),


        "Holdings":

            latest.get(
                "holdings",
                pd.DataFrame(),
            ),

    }

    missing = [

        report

        for report, dataframe

        in required.items()

        if dataframe.empty

    ]

    if not missing:

        return True

    empty_state(

        "Risk Reports Missing",

        (
            "The following reports "
            "are unavailable:\n\n"

            + "\n".join(
                f"• {item}"
                for item in missing
            )

            + "\n\nRun the workflow "
              "to regenerate reports."

        ),

    )

    return False


if not validate_reports(
    reports,
):

    st.stop()

# =============================================================================
# Working Reports
# =============================================================================

portfolio_summary = latest.get(

    "portfolio_summary",

    pd.DataFrame(),

)


holdings = latest.get(

    "holdings",

    pd.DataFrame(),

)


risk_summary = latest.get(

    "risk_summary",

    pd.DataFrame(),

)


risk_history = history.get(

    "risk_history",

    pd.DataFrame(),

)

# =============================================================================
# Page Header
# =============================================================================

section(

    "Portfolio Risk Dashboard",

    (
        "Executive overview of the "
        "latest workflow-generated "
        "risk reports."
    ),

)

risk_kpis(

    risk_summary,

)

divider()

# =============================================================================
# Executive Risk Summary
# =============================================================================

section(

    "Executive Risk Summary",

    (
        "Summary of portfolio risk "
        "metrics generated by the "
        "workflow."
    ),

)

if risk_summary.empty:

    st.info(
        "Risk summary is unavailable."
    )

else:

    st.dataframe(

        risk_summary,

        use_container_width=True,

        hide_index=True,

    )

    dataframe_info(
        risk_summary,
    )

divider()

# =============================================================================
# Portfolio Exposure Analytics
# =============================================================================

section(
    "Portfolio Exposure",
    (
        "Portfolio allocation and "
        "exposure based on the latest "
        "holdings report."
    ),
)

sector_column = None

for column in (

    "Sector",

    "Sector Name",

):

    if column in holdings.columns:

        sector_column = column

        break

weight_column = None

for column in (

    "Portfolio Weight",

    "Weight",

    "Weight (%)",

    "Current Weight",

):

    if column in holdings.columns:

        weight_column = column

        break

symbol_column = None

for column in (

    "Symbol",

    "Ticker",

    "Stock",

):

    if column in holdings.columns:

        symbol_column = column

        break

left_col, right_col = st.columns(2)

# =============================================================================
# Sector Exposure
# =============================================================================

with left_col:

    st.subheader(
        "Sector Allocation"
    )

    if (

        sector_column is not None

        and

        weight_column is not None

    ):

        sector_exposure = (

            holdings

            .groupby(
                sector_column,
                dropna=False,
            )[weight_column]

            .sum()

            .reset_index()

            .sort_values(

                weight_column,

                ascending=False,

            )

        )

        figure = px.bar(

            sector_exposure,

            x=sector_column,

            y=weight_column,

            color=weight_column,

            text=weight_column,

        )

        figure.update_layout(

            height=CONFIG.chart_height,

            xaxis_title="",

            yaxis_title="Portfolio Weight",

            coloraxis_showscale=False,

        )

        figure.update_traces(

            textposition="outside",

        )

        st.plotly_chart(

            figure,

            use_container_width=True,

        )

    else:

        st.info(
            "Sector allocation "
            "is unavailable."
        )

# =============================================================================
# Position Exposure
# =============================================================================

with right_col:

    st.subheader(
        "Largest Positions"
    )

    if (

        symbol_column is not None

        and

        weight_column is not None

    ):

        top_positions = (

            holdings

            .sort_values(

                weight_column,

                ascending=False,

            )

            .head(
                CONFIG.top_positions,
            )

        )

        figure = px.bar(

            top_positions,

            x=weight_column,

            y=symbol_column,

            orientation="h",

            color=weight_column,

            text=weight_column,

        )

        figure.update_layout(

            height=CONFIG.chart_height,

            yaxis=dict(
                autorange="reversed",
            ),

            xaxis_title="Portfolio Weight",

            yaxis_title="",

            coloraxis_showscale=False,

        )

        figure.update_traces(

            textposition="outside",

        )

        st.plotly_chart(

            figure,

            use_container_width=True,

        )

    else:

        st.info(
            "Position exposure "
            "is unavailable."
        )

divider()

# =============================================================================
# Concentration Overview
# =============================================================================

section(
    "Concentration Overview",
    (
        "Largest portfolio positions "
        "from the workflow report."
    ),
)

if (

    symbol_column is not None

    and

    weight_column is not None

):

    concentration = (

        holdings

        .sort_values(

            weight_column,

            ascending=False,

        )

        .head(10)

    )

    holdings_table(

        concentration,

        key="risk_concentration",

    )

    dataframe_info(
        concentration,
    )

else:

    st.info(
        "Concentration report "
        "is unavailable."
    )

divider()

# =============================================================================
# Risk Heatmap
# =============================================================================

section(
    "Risk Heatmap",
    (
        "Visual distribution of "
        "portfolio holdings."
    ),
)

return_column = None

for column in (

    "Return",

    "Return (%)",

    "P/L %",

):

    if column in holdings.columns:

        return_column = column

        break

if (

    symbol_column is not None

    and

    weight_column is not None

    and

    return_column is not None

):

    figure = px.scatter(

        holdings,

        x=weight_column,

        y=return_column,

        color=sector_column

        if sector_column

        else None,

        hover_name=symbol_column,

        size=weight_column,

        size_max=40,

    )

    figure.update_layout(

        height=550,

        xaxis_title="Portfolio Weight",

        yaxis_title="Return",

    )

    st.plotly_chart(

        figure,

        use_container_width=True,

    )

else:

    st.info(
        "Risk heatmap "
        "is unavailable."
    )

divider()

# =============================================================================
# Drawdown Analysis
# =============================================================================

section(
    "Drawdown Analysis",
    (
        "Historical drawdown metrics "
        "generated by the workflow."
    ),
)

drawdown_columns = [

    column

    for column in (

        "Current Drawdown",

        "Maximum Drawdown",

        "Average Drawdown",

        "Drawdown",

    )

    if column in risk_summary.columns

]

if (

    not risk_summary.empty

    and

    drawdown_columns

):

    drawdown_data = risk_summary[
        drawdown_columns
    ]

    st.dataframe(

        drawdown_data,

        use_container_width=True,

        hide_index=True,

    )

else:

    st.info(
        "Drawdown report "
        "is unavailable."
    )

divider()

# =============================================================================
# Value at Risk
# =============================================================================

section(
    "Value at Risk",
    (
        "Portfolio Value at Risk "
        "reported by the workflow."
    ),
)

var_columns = [

    column

    for column in (

        "VaR 90%",

        "VaR 95%",

        "VaR 99%",

        "VaR",

    )

    if column in risk_summary.columns

]

if (

    not risk_summary.empty

    and

    var_columns

):

    var_data = (

        risk_summary[
            var_columns
        ]

        .T

        .reset_index()

    )

    var_data.columns = [

        "Confidence",

        "VaR",

    ]

    left, right = st.columns(
        [1, 2],
    )

    with left:

        st.dataframe(

            var_data,

            use_container_width=True,

            hide_index=True,

        )

    with right:

        figure = px.bar(

            var_data,

            x="Confidence",

            y="VaR",

            text="VaR",

            color="VaR",

        )

        figure.update_layout(

            height=CONFIG.chart_height,

            coloraxis_showscale=False,

        )

        st.plotly_chart(

            figure,

            use_container_width=True,

        )

else:

    st.info(
        "VaR report is unavailable."
    )

divider()

# =============================================================================
# Conditional Value at Risk
# =============================================================================

section(
    "Conditional Value at Risk",
    (
        "Expected tail loss reported "
        "by the workflow."
    ),
)

cvar_columns = [

    column

    for column in (

        "CVaR 90%",

        "CVaR 95%",

        "CVaR 99%",

        "CVaR",

    )

    if column in risk_summary.columns

]

if (

    not risk_summary.empty

    and

    cvar_columns

):

    cvar_data = (

        risk_summary[
            cvar_columns
        ]

        .T

        .reset_index()

    )

    cvar_data.columns = [

        "Confidence",

        "CVaR",

    ]

    st.dataframe(

        cvar_data,

        use_container_width=True,

        hide_index=True,

    )

else:

    st.info(
        "CVaR report is unavailable."
    )

divider()

# =============================================================================
# Historical Risk Trend
# =============================================================================

section(
    "Historical Risk Trend",
    (
        "Portfolio risk history."
    ),
)

if (

    not risk_history.empty

):

    date_column = next(

        (

            column

            for column in (

                "Date",

                "Timestamp",

                "Scan Date",

            )

            if column in risk_history.columns

        ),

        None,

    )

    score_column = next(

        (

            column

            for column in (

                "Portfolio Health",

                "Risk Score",

                "Health Score",

            )

            if column in risk_history.columns

        ),

        None,

    )

    if (

        date_column

        and

        score_column

    ):

        figure = px.line(

            risk_history,

            x=date_column,

            y=score_column,

            markers=True,

        )

        figure.update_layout(

            height=420,

            xaxis_title="",

            yaxis_title=score_column,

        )

        st.plotly_chart(

            figure,

            use_container_width=True,

        )

        holdings_table(

            risk_history.tail(20),

            key="risk_history",

        )

    else:

        st.info(
            "Historical risk trend "
            "is unavailable."
        )

else:

    st.info(
        "Risk history "
        "is unavailable."
    )

divider()

# =============================================================================
# Risk Ranking
# =============================================================================

section(
    "Risk Ranking",
    (
        "Highest weighted portfolio "
        "positions."
    ),
)

if (

    symbol_column

    and

    weight_column

):

    ranking = (

        holdings

        .sort_values(

            weight_column,

            ascending=False,

        )

        .head(25)

    )

    holdings_table(

        ranking,

        key="risk_ranking",

    )

    dataframe_info(
        ranking,
    )

else:

    st.info(
        "Risk ranking "
        "is unavailable."
    )

divider()
# =============================================================================
# Risk Alerts
# =============================================================================

section(
    "Risk Alerts",
    (
        "Important workflow-generated "
        "portfolio risk notifications."
    ),
)

alerts = pd.DataFrame()

if (

    not risk_summary.empty

    and

    "Alert" in risk_summary.columns

):

    alert_columns = [

        column

        for column in (

            "Alert",

            "Description",

            "Severity",

            "Status",

        )

        if column in risk_summary.columns

    ]

    alerts = risk_summary[
        alert_columns
    ]

if alerts.empty:

    st.success(
        "No active risk alerts.",
        icon="✅",
    )

else:

    holdings_table(

        alerts,

        key="risk_alerts",

    )

divider()

# =============================================================================
# Portfolio Risk Limits
# =============================================================================

section(
    "Portfolio Risk Limits",
    (
        "Workflow compliance against "
        "configured portfolio limits."
    ),
)

limit_columns = [

    column

    for column in (

        "Rule",

        "Limit",

        "Current",

        "Status",

    )

    if column in risk_summary.columns

]

if (

    not risk_summary.empty

    and

    len(limit_columns) >= 4

):

    limits = risk_summary[
        limit_columns
    ]

    holdings_table(

        limits,

        key="risk_limits",

    )

else:

    st.info(
        "Risk limit report "
        "is unavailable."
    )

divider()

# =============================================================================
# Compliance Summary
# =============================================================================

section(
    "Compliance Summary",
    (
        "Workflow compliance overview."
    ),
)

if (

    not risk_summary.empty

    and

    "Status" in risk_summary.columns

):

    status = (

        risk_summary["Status"]

        .astype(str)

        .str.upper()

    )

    passed = int(
        (status == "PASS").sum()
    )

    failed = int(
        (status == "FAIL").sum()
    )

    warning = int(
        (status == "WARNING").sum()
    )

    col1, col2, col3 = st.columns(3)

    with col1:

        st.metric(
            "Passed",
            passed,
        )

    with col2:

        st.metric(
            "Failed",
            failed,
        )

    with col3:

        st.metric(
            "Warnings",
            warning,
        )

else:

    st.info(
        "Compliance summary "
        "is unavailable."
    )

divider()

# =============================================================================
# Report Status
# =============================================================================

section(
    "Report Status",
    (
        "Reports currently loaded "
        "by this page."
    ),
)

status = pd.DataFrame(

    [

        {

            "Report": "Portfolio Summary",

            "Rows": len(
                portfolio_summary,
            ),

            "Status":

                "Available"

                if not portfolio_summary.empty

                else "Missing",

        },

        {

            "Report": "Holdings",

            "Rows": len(
                holdings,
            ),

            "Status":

                "Available"

                if not holdings.empty

                else "Missing",

        },

        {

            "Report": "Risk Summary",

            "Rows": len(
                risk_summary,
            ),

            "Status":

                "Available"

                if not risk_summary.empty

                else "Missing",

        },

        {

            "Report": "Risk History",

            "Rows": len(
                risk_history,
            ),

            "Status":

                "Available"

                if not risk_history.empty

                else "Missing",

        },

    ]

)

st.dataframe(

    status,

    use_container_width=True,

    hide_index=True,

)

divider()

# =============================================================================
# Quick Navigation
# =============================================================================

section(
    "Explore Reports",
    (
        "Navigate to other workflow "
        "reports using the sidebar."
    ),
)

left, right = st.columns(2)

with left:

    st.info(
        """
📁 **Portfolio**

Portfolio overview
and allocation.
"""
    )

    st.info(
        """
💼 **Holdings**

Current portfolio
positions.
"""
    )

    st.info(
        """
📊 **Daily Monitor**

Scanner output
and opportunities.
"""
    )

with right:

    st.info(
        """
📈 **Performance**

Portfolio performance
analytics.
"""
    )

    st.info(
        """
⚙️ **Execution**

Execution summary
and history.
"""
    )

    st.info(
        """
📥 **Downloads**

Export workflow
reports.
"""
    )

divider()

# =============================================================================
# Footer
# =============================================================================

st.caption(
    "Institutional Scanner Monitor"
)

st.caption(
    "Portfolio Risk Dashboard"
)

st.caption(
    (
        "Executive Risk Reporting • "
        "Workflow Report Viewer"
    )
)