"""
pages/06_Performance.py
=======================

Institutional Scanner Monitor

Performance Dashboard

Displays workflow-generated
portfolio performance reports.
"""

from __future__ import annotations

from dataclasses import dataclass

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

from core.logger import get_logger
from core.session import (
    initialize as initialize_session,
)
from core.theme import (
    apply_theme,
    inject_card_css,
)

from ui.cards import (
    divider,
    empty_state,
    section,
)

from ui.loader import (
    ReportData,
    load_reports,
)

from ui.metrics import (
    dataframe_info,
    performance_kpis,
)

from ui.sidebar import (
    render_sidebar,
)

from ui.tables import (
    holdings_table,
)

LOGGER = get_logger(__name__)

# =============================================================================
# Configuration
# =============================================================================


@dataclass(slots=True, frozen=True)
class PerformanceConfig:
    """
    Performance dashboard configuration.
    """

    page_title: str = "Performance"

    page_icon: str = "📈"

    layout: str = "wide"

    chart_height: int = 420

    preview_rows: int = 20

    top_holdings: int = 15


CONFIG = PerformanceConfig()

# =============================================================================
# Streamlit Configuration
# =============================================================================

st.set_page_config(

    page_title=CONFIG.page_title,

    page_icon=CONFIG.page_icon,

    layout=CONFIG.layout,

)

apply_theme()

inject_card_css()

render_sidebar()

initialize_session()

# =============================================================================
# Report Loading
# =============================================================================


@st.cache_data(show_spinner=False)
def get_reports() -> ReportData:
    """
    Load workflow reports.
    """

    return load_reports()


try:

    reports = get_reports()

    latest = reports.latest

    history = reports.history

except Exception:

    LOGGER.exception(
        "Unable to load performance reports."
    )

    st.error(
        "Unable to load performance reports."
    )

    st.stop()

# =============================================================================
# Validation
# =============================================================================


def validate_reports(
    reports: ReportData,
) -> bool:
    """
    Validate required reports.
    """

    required = {

        "Portfolio Summary":

            latest.get(
                "portfolio_summary",
                pd.DataFrame(),
            ),


        "Holdings":

            latest.get(
                "holdings",
                pd.DataFrame(),
            ),

    
        "Performance History":

            history.get(
                "performance_history",
                pd.DataFrame(),
            ),

    }

    missing = [

        report

        for report, dataframe

        in required.items()

        if dataframe.empty

    ]

    if not missing:

        return True

    empty_state(

        "Performance Reports Missing",

        (
            "The following reports "
            "are unavailable:\n\n"

            + "\n".join(
                f"• {report}"
                for report in missing
            )

            + "\n\nRun the workflow "
              "to regenerate reports."

        ),

    )

    return False


if not validate_reports(
    reports,
):

    st.stop()

# =============================================================================
# Working Reports
# =============================================================================

portfolio_summary = latest.get(

    "portfolio_summary",

    pd.DataFrame(),

)


holdings = latest.get(

    "holdings",

    pd.DataFrame(),

)


performance_history = history.get(

    "performance_history",

    pd.DataFrame(),

)

# =============================================================================
# Page Header
# =============================================================================

section(

    "Portfolio Performance",

    (
        "Executive overview of the "
        "latest workflow-generated "
        "performance reports."
    ),

)

performance_kpis(

    portfolio_summary,

)

divider()

# =============================================================================
# Executive Performance Summary
# =============================================================================

section(

    "Executive Performance Summary",

    (
        "Summary of portfolio "
        "performance metrics "
        "generated by the workflow."
    ),

)

if portfolio_summary.empty:

    st.info(
        "Portfolio summary is unavailable."
    )

else:

    st.dataframe(

        portfolio_summary,

        use_container_width=True,

        hide_index=True,

    )

    dataframe_info(
        portfolio_summary,
    )

divider()

# =============================================================================
# Portfolio Growth
# =============================================================================

section(

    "Portfolio Growth",

    (
        "Historical portfolio growth "
        "from workflow-generated "
        "performance reports."
    ),

)

date_column = None

for column in (

    "Date",

    "Timestamp",

    "Trade Date",

):

    if column in performance_history.columns:

        date_column = column

        break

value_column = None

for column in (

    "Portfolio Value",

    "Current Value",

    "Net Value",

    "Portfolio Equity",

):

    if column in performance_history.columns:

        value_column = column

        break

if (

    date_column

    and

    value_column

):

    figure = px.line(

        performance_history,

        x=date_column,

        y=value_column,

        markers=True,

        title="Portfolio Growth",

    )

    figure.update_layout(

        height=CONFIG.chart_height,

        xaxis_title="",

        yaxis_title=value_column,

    )

    st.plotly_chart(

        figure,

        use_container_width=True,

    )

else:

    st.info(
        "Portfolio growth "
        "is unavailable."
    )

divider()

# =============================================================================
# Historical Performance
# =============================================================================

section(

    "Historical Performance",

    (
        "Latest performance history."
    ),

)

if performance_history.empty:

    st.info(
        "Performance history "
        "is unavailable."
    )

else:

    holdings_table(

        performance_history,

        key="performance_history",

    )

    dataframe_info(
        performance_history,
    )

divider()

# =============================================================================
# Return Distribution
# =============================================================================

section(

    "Return Distribution",

    (
        "Distribution of portfolio "
        "returns from history."
    ),

)

return_column = None

for column in (

    "Return",

    "Return (%)",

    "Portfolio Return",

    "Daily Return",

):

    if column in performance_history.columns:

        return_column = column

        break

if return_column:

    left, right = st.columns(
        [2, 1],
    )

    with left:

        figure = px.histogram(

            performance_history,

            x=return_column,

            nbins=30,

            title="Return Distribution",

        )

        figure.update_layout(

            height=CONFIG.chart_height,

        )

        st.plotly_chart(

            figure,

            use_container_width=True,

        )

    with right:

        summary = (

            performance_history[
                return_column
            ]

            .describe()

            .reset_index()

        )

        summary.columns = [

            "Statistic",

            "Value",

        ]

        st.dataframe(

            summary,

            use_container_width=True,

            hide_index=True,

        )

else:

    st.info(
        "Return distribution "
        "is unavailable."
    )

divider()

# =============================================================================
# Rolling Performance
# =============================================================================

section(

    "Rolling Performance",

    (
        "Trend of reported "
        "portfolio performance."
    ),

)

if (

    date_column

    and

    return_column

):

    figure = px.line(

        performance_history,

        x=date_column,

        y=return_column,

        markers=True,

        title="Performance Trend",

    )

    figure.update_layout(

        height=CONFIG.chart_height,

        xaxis_title="",

        yaxis_title=return_column,

    )

    st.plotly_chart(

        figure,

        use_container_width=True,

    )

else:

    st.info(
        "Performance trend "
        "is unavailable."
    )

divider()

# =============================================================================
# Benchmark Comparison
# =============================================================================

section(

    "Benchmark Comparison",

    (
        "Portfolio performance versus "
        "benchmark reported by the "
        "workflow."
    ),

)

benchmark_column = None

for column in (

    "Benchmark Return",

    "Benchmark",

    "Index Return",

):

    if column in performance_history.columns:

        benchmark_column = column

        break

if (

    date_column

    and

    return_column

    and

    benchmark_column

):

    benchmark = (

        performance_history[

            [

                date_column,

                return_column,

                benchmark_column,

            ]

        ]

        .melt(

            id_vars=date_column,

            var_name="Series",

            value_name="Return",

        )

    )

    figure = px.line(

        benchmark,

        x=date_column,

        y="Return",

        color="Series",

        markers=True,

    )

    figure.update_layout(

        height=CONFIG.chart_height,

        xaxis_title="",

        yaxis_title="Return",

    )

    st.plotly_chart(

        figure,

        use_container_width=True,

    )

else:

    st.info(
        "Benchmark comparison "
        "is unavailable."
    )

divider()

# =============================================================================
# Sector Attribution
# =============================================================================

section(

    "Sector Attribution",

    (
        "Portfolio contribution by "
        "sector."
    ),

)

sector_column = None

for column in (

    "Sector",

    "Sector Name",

):

    if column in holdings.columns:

        sector_column = column

        break

weight_column = None

for column in (

    "Portfolio Weight",

    "Weight",

    "Weight (%)",

):

    if column in holdings.columns:

        weight_column = column

        break

if (

    sector_column

    and

    weight_column

):

    sector = (

        holdings

        .groupby(

            sector_column,

            dropna=False,

        )[

            weight_column

        ]

        .sum()

        .reset_index()

        .sort_values(

            weight_column,

            ascending=False,

        )

    )

    left, right = st.columns(
        [2, 1],
    )

    with left:

        figure = px.bar(

            sector,

            x=sector_column,

            y=weight_column,

            text=weight_column,

            color=weight_column,

        )

        figure.update_layout(

            height=CONFIG.chart_height,

            coloraxis_showscale=False,

        )

        st.plotly_chart(

            figure,

            use_container_width=True,

        )

    with right:

        st.dataframe(

            sector,

            use_container_width=True,

            hide_index=True,

        )

else:

    st.info(
        "Sector attribution "
        "is unavailable."
    )

divider()

# =============================================================================
# Top Performers
# =============================================================================

section(

    "Top Performers",

    (
        "Highest performing holdings."
    ),

)

symbol_column = None

for column in (

    "Symbol",

    "Ticker",

    "Stock",

):

    if column in holdings.columns:

        symbol_column = column

        break

holding_return = None

for column in (

    "Return",

    "Return (%)",

    "P/L %",

):

    if column in holdings.columns:

        holding_return = column

        break

if (

    symbol_column

    and

    holding_return

):

    winners = (

        holdings

        .sort_values(

            holding_return,

            ascending=False,

        )

        .head(10)

    )

    holdings_table(

        winners,

        key="top_performers",

    )

else:

    st.info(
        "Top performers "
        "are unavailable."
    )

divider()

# =============================================================================
# Bottom Performers
# =============================================================================

section(

    "Bottom Performers",

    (
        "Lowest performing holdings."
    ),

)

if (

    symbol_column

    and

    holding_return

):

    losers = (

        holdings

        .sort_values(

            holding_return,

            ascending=True,

        )

        .head(10)

    )

    holdings_table(

        losers,

        key="bottom_performers",

    )

else:

    st.info(
        "Bottom performers "
        "are unavailable."
    )

divider()

# =============================================================================
# Performance Ranking
# =============================================================================

section(

    "Performance Ranking",

    (
        "Performance ranking of "
        "portfolio holdings."
    ),

)

if (

    symbol_column

    and

    holding_return

):

    ranking = (

        holdings

        .sort_values(

            holding_return,

            ascending=False,

        )

    )

    holdings_table(

        ranking,

        key="performance_ranking",

    )

    dataframe_info(
        ranking,
    )

else:

    st.info(
        "Performance ranking "
        "is unavailable."
    )

divider()

# =============================================================================
# Performance Metrics
# =============================================================================

section(

    "Performance Metrics",

    (
        "Executive performance metrics "
        "reported by the workflow."
    ),

)

metric_columns = [

    column

    for column in (

        "Total Return",

        "Annual Return",

        "CAGR",

        "Sharpe Ratio",

        "Sortino Ratio",

        "Calmar Ratio",

        "Alpha",

        "Beta",

        "Maximum Drawdown",

    )

    if column in portfolio_summary.columns

]

if (

    not portfolio_summary.empty

    and

    metric_columns

):

    metrics = portfolio_summary[
        metric_columns
    ]

    st.dataframe(

        metrics,

        use_container_width=True,

        hide_index=True,

    )

else:

    st.info(
        "Performance metrics "
        "are unavailable."
    )

divider()

# =============================================================================
# Report Status
# =============================================================================

section(

    "Report Status",

    (
        "Workflow reports currently "
        "loaded by this dashboard."
    ),

)

status = pd.DataFrame(

    [

        {

            "Report": "Portfolio Summary",

            "Rows": len(
                portfolio_summary,
            ),

            "Status":

                "Available"

                if not portfolio_summary.empty

                else "Missing",

        },

        {

            "Report": "Holdings",

            "Rows": len(
                holdings,
            ),

            "Status":

                "Available"

                if not holdings.empty

                else "Missing",

        },

        {

            "Report": "Performance History",

            "Rows": len(
                performance_history,
            ),

            "Status":

                "Available"

                if not performance_history.empty

                else "Missing",

        },

    ]

)

st.dataframe(

    status,

    use_container_width=True,

    hide_index=True,

)

divider()

# =============================================================================
# Data Quality
# =============================================================================

section(

    "Data Quality",

    (
        "Overview of the loaded "
        "workflow reports."
    ),

)

quality_col1, quality_col2, quality_col3 = st.columns(3)

with quality_col1:

    st.metric(
        "Portfolio Records",
        len(portfolio_summary),
    )

with quality_col2:

    st.metric(
        "Holdings",
        len(holdings),
    )

with quality_col3:

    st.metric(
        "Performance History",
        len(performance_history),
    )

divider()

# =============================================================================
# Explore Reports
# =============================================================================

section(

    "Explore Reports",

    (
        "Navigate through the "
        "Institutional Scanner Monitor."
    ),

)

left, right = st.columns(2)

with left:

    st.info(
        """
📊 **Dashboard**

Executive overview.
"""
    )

    st.info(
        """
💼 **Portfolio**

Portfolio summary.
"""
    )

    st.info(
        """
📁 **Holdings**

Current holdings.
"""
    )

with right:

    st.info(
        """
📈 **Daily Monitor**

Latest scanner output.
"""
    )

    st.info(
        """
🛡️ **Risk**

Portfolio risk reports.
"""
    )

    st.info(
        """
⚙️ **Execution**

Execution reports.
"""
    )

divider()

# =============================================================================
# Footer
# =============================================================================

st.caption(
    "Institutional Scanner Monitor"
)

st.caption(
    "Performance Dashboard"
)

st.caption(
    (
        "Workflow Report Viewer • "
        "Portfolio Performance Analytics"
    )
)