"""
pages/07_Execution.py
=====================

Institutional Scanner Monitor

Execution Dashboard

Displays workflow-generated
execution reports.
"""

from __future__ import annotations

from dataclasses import dataclass

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

from core.logger import get_logger
from core.session import (
    initialize as initialize_session,
)
from core.theme import (
    apply_theme,
    inject_card_css,
)

from ui.cards import (
    divider,
    empty_state,
    section,
)

from ui.loader import (
    ReportData,
    load_reports,
)

from ui.metrics import (
    dataframe_info,
    execution_kpis,
)

from ui.sidebar import (
    render_sidebar,
)

from ui.tables import (
    holdings_table,
)

LOGGER = get_logger(__name__)

# =============================================================================
# Configuration
# =============================================================================


@dataclass(slots=True, frozen=True)
class ExecutionConfig:
    """
    Execution dashboard configuration.
    """

    page_title: str = "Execution"

    page_icon: str = "⚡"

    layout: str = "wide"

    chart_height: int = 420

    preview_rows: int = 25

    top_orders: int = 20


CONFIG = ExecutionConfig()

# =============================================================================
# Streamlit Configuration
# =============================================================================

st.set_page_config(

    page_title=CONFIG.page_title,

    page_icon=CONFIG.page_icon,

    layout=CONFIG.layout,

)

apply_theme()

inject_card_css()

render_sidebar()

initialize_session()

# =============================================================================
# Report Loading
# =============================================================================


@st.cache_data(show_spinner=False)
def get_reports() -> ReportData:
    """
    Load workflow reports.
    """

    return load_reports()


try:

    reports = get_reports()

    latest = reports.latest

    history = reports.history

except Exception:

    LOGGER.exception(
        "Unable to load execution reports."
    )

    st.error(
        "Unable to load execution reports."
    )

    st.stop()

# =============================================================================
# Validation
# =============================================================================


def validate_reports(
    reports: ReportData,
) -> bool:
    """
    Validate required reports.
    """

    required = {

        "Execution Summary":

            latest.get(
                "execution_summary",
                pd.DataFrame(),
            ),

    }

    missing = [

        report

        for report, dataframe

        in required.items()

        if dataframe.empty

    ]

    if not missing:

        return True

    empty_state(

        "Execution Reports Missing",

        (
            "The following reports "
            "are unavailable:\n\n"

            + "\n".join(
                f"• {report}"
                for report in missing
            )

            + "\n\nRun the workflow "
              "to regenerate reports."

        ),

    )

    return False


if not validate_reports(
    reports,
):

    st.stop()

# =============================================================================
# Working Reports
# =============================================================================

orders = latest.get(

    "orders",

    pd.DataFrame(),

)


trade_list = latest.get(

    "trade_list",

    pd.DataFrame(),

)


rebalance_orders = latest.get(

    "rebalance_orders",

    pd.DataFrame(),

)


execution_summary = latest.get(

    "execution_summary",

    pd.DataFrame(),

)


execution_history = history.get(

    "execution_history",

    pd.DataFrame(),

)

# =============================================================================
# Page Header
# =============================================================================

section(

    "Execution Dashboard",

    (
        "Executive overview of the "
        "latest workflow-generated "
        "execution reports."
    ),

)

execution_kpis(

    execution_summary,

)

divider()

# =============================================================================
# Executive Execution Summary
# =============================================================================

section(

    "Executive Execution Summary",

    (
        "Summary of execution metrics "
        "generated by the workflow."
    ),

)

if execution_summary.empty:

    st.info(
        "Execution summary is unavailable."
    )

else:

    st.dataframe(

        execution_summary,
        use_container_width=True,
        hide_index=True,

    )

    dataframe_info(
        execution_summary,
    )

divider()

# =============================================================================
# Order Management
# =============================================================================

section(

    "Order Management",

    (
        "Review workflow-generated "
        "orders and execution status."
    ),

)

# =============================================================================
# Order Queue
# =============================================================================

st.subheader(
    "Order Queue"
)

if orders.empty:

    st.info(
        "Order queue is unavailable."
    )

else:

    holdings_table(

        orders,

        key="execution_orders",

    )

    dataframe_info(
        orders,
    )

divider()

# =============================================================================
# Trade Blotter
# =============================================================================

section(

    "Trade Blotter",

    (
        "Latest executed trades "
        "generated by the workflow."
    ),

)
if trade_list.empty:

    st.info(
        "No trade blotter available. "
        "The workflow did not generate trade-level execution records."
    )

else:

    holdings_table(

        trade_list,

        key="trade_blotter",

    )


divider()

# =============================================================================
# Pending Orders
# =============================================================================

section(

    "Pending Orders",

    (
        "Orders awaiting execution."
    ),

)

status_column = None

for column in (

    "Status",

    "Order Status",

):

    if column in orders.columns:

        status_column = column

        break

if (

    status_column

    and

    not orders.empty

):

    pending_orders = (

        orders[

            orders[
                status_column
            ]

            .astype(str)

            .str.upper()

            .isin(

                [

                    "PENDING",

                    "OPEN",

                ]

            )

        ]

    )

    if pending_orders.empty:

        st.success(
            "No pending orders.",
            icon="✅",
        )

    else:

        holdings_table(

            pending_orders,

            key="pending_orders",

        )

else:

    st.info(
        "Pending order report "
        "is unavailable."
    )

divider()

# =============================================================================
# Executed Orders
# =============================================================================

section(

    "Executed Orders",

    (
        "Successfully executed "
        "workflow orders."
    ),

)

if (

    status_column

    and

    not orders.empty

):

    executed_orders = (

        orders[

            orders[
                status_column
            ]

            .astype(str)

            .str.upper()

            .isin(

                [

                    "EXECUTED",

                    "FILLED",

                    "COMPLETED",

                ]

            )

        ]

    )

    if executed_orders.empty:

        st.info(
            "No executed orders."
        )

    else:

        holdings_table(

            executed_orders,

            key="executed_orders",

        )

else:

    st.info(
        "Executed order report "
        "is unavailable."
    )

divider()

# =============================================================================
# Failed Orders
# =============================================================================

section(

    "Failed Orders",

    (
        "Orders rejected or "
        "cancelled."
    ),

)

if (

    status_column

    and

    not orders.empty

):

    failed_orders = (

        orders[

            orders[
                status_column
            ]

            .astype(str)

            .str.upper()

            .isin(

                [

                    "FAILED",

                    "REJECTED",

                    "CANCELLED",

                ]

            )

        ]

    )

    if failed_orders.empty:

        st.success(
            "No failed orders.",
            icon="✅",
        )

    else:

        holdings_table(

            failed_orders,

            key="failed_orders",

        )

else:

    st.info(
        "Failed order report "
        "is unavailable."
    )

divider()

# =============================================================================
# Rebalance Orders
# =============================================================================

section(

    "Rebalance Orders",

    (
        "Portfolio rebalance "
        "orders generated by "
        "the workflow."
    ),

)

if rebalance_orders.empty:

    st.info(
        "Rebalance orders "
        "are unavailable."
    )

else:

    holdings_table(

        rebalance_orders,

        key="rebalance_orders",

    )

    dataframe_info(
        rebalance_orders,
    )

divider()

# =============================================================================
# Execution Timeline
# =============================================================================

section(

    "Execution Timeline",

    (
        "Historical execution "
        "activity generated by "
        "the workflow."
    ),

)

date_column = None

for column in (

    "Date",

    "Trade Date",

    "Execution Date",

    "Timestamp",

):

    if column in execution_history.columns:

        date_column = column

        break

count_column = None

for column in (

    "Executed Orders",

    "Orders",

    "Trades",

    "Executions",

):

    if column in execution_history.columns:

        count_column = column

        break

if (

    date_column

    and

    count_column

):

    figure = px.line(

        execution_history,

        x=date_column,

        y=count_column,

        markers=True,

        title="Execution Trend",

    )

    figure.update_layout(

        height=CONFIG.chart_height,

        xaxis_title="",

        yaxis_title=count_column,

    )

    st.plotly_chart(

        figure,

        use_container_width=True,

    )

else:

    st.info(
        "Execution timeline "
        "is unavailable."
    )

divider()

# =============================================================================
# Broker Analytics
# =============================================================================

section(

    "Broker Analytics",

    (
        "Execution grouped by "
        "broker."
    ),

)

broker_column = None

for column in (

    "Broker",

    "Broker Name",

):

    if column in trade_list.columns:

        broker_column = column

        break

if (

    broker_column

    and

    not trade_list.empty

):

    broker_summary = (

        trade_list

        .groupby(

            broker_column,

            dropna=False,

        )

        .size()

        .reset_index(

            name="Trades",

        )

        .sort_values(

            "Trades",

            ascending=False,

        )

    )

    left, right = st.columns(
        [2, 1],
    )

    with left:

        figure = px.bar(

            broker_summary,

            x=broker_column,

            y="Trades",

            text="Trades",

        )

        figure.update_layout(

            height=CONFIG.chart_height,

        )

        st.plotly_chart(

            figure,

            use_container_width=True,

        )

    with right:

        st.dataframe(

            broker_summary,

            use_container_width=True,

            hide_index=True,

        )

else:

    st.info(
        "Broker analytics "
        "are unavailable."
    )

divider()

# =============================================================================
# Execution Cost
# =============================================================================

section(

    "Execution Cost",

    (
        "Transaction cost "
        "reported by the workflow."
    ),

)

cost_column = None

for column in (

    "Transaction Cost",

    "Execution Cost",

    "Cost",

    "Brokerage",

):

    if column in trade_list.columns:

        cost_column = column

        break

if (

    cost_column

    and

    not trade_list.empty

):

    figure = px.histogram(

        trade_list,

        x=cost_column,

        nbins=30,

        title="Execution Cost Distribution",

    )

    figure.update_layout(

        height=CONFIG.chart_height,

    )

    st.plotly_chart(

        figure,

        use_container_width=True,

    )

else:

    st.info(
        "Execution cost "
        "is unavailable."
    )

divider()

# =============================================================================
# Slippage Analysis
# =============================================================================

section(

    "Slippage Analysis",

    (
        "Workflow-reported "
        "execution slippage."
    ),

)

slippage_column = None

for column in (

    "Slippage",

    "Slippage (%)",

    "Execution Slippage",

):

    if column in trade_list.columns:

        slippage_column = column

        break

symbol_column = None

for column in (

    "Symbol",

    "Ticker",

    "Stock",

):

    if column in trade_list.columns:

        symbol_column = column

        break

if (

    not trade_list.empty

    and

    slippage_column is not None

    and

    symbol_column is not None

):

    figure = px.scatter(

        trade_list,

        x=slippage_column,

        y=symbol_column,

        color=slippage_column,

        hover_name=symbol_column,

    )

    figure.update_layout(

        height=CONFIG.chart_height,

        xaxis_title=slippage_column,

        yaxis_title="",

        coloraxis_showscale=False,

    )

    st.plotly_chart(

        figure,

        use_container_width=True,

    )

else:

    st.info(
        "Slippage report "
        "is unavailable."
    )

divider()

# =============================================================================
# Execution History
# =============================================================================

section(

    "Execution History",

    (
        "Historical execution "
        "records."
    ),

)

if execution_history.empty:

    st.info(
        "Execution history "
        "is unavailable."
    )

else:

    holdings_table(

        execution_history,

        key="execution_history",

    )

    dataframe_info(
        execution_history,
    )

divider()

# =============================================================================
# Execution Scorecard
# =============================================================================

section(

    "Execution Scorecard",

    (
        "Executive summary of "
        "workflow-generated execution "
        "metrics."
    ),

)

if execution_summary.empty:

    st.info(
        "Execution summary "
        "is unavailable."
    )

else:

    st.dataframe(

        execution_summary,

        use_container_width=True,

        hide_index=True,

    )

divider()

# =============================================================================
# Execution Alerts
# =============================================================================

section(

    "Execution Alerts",

    (
        "Execution alerts reported "
        "by the workflow."
    ),

)

alert_columns = [

    column

    for column in (

        "Alert",

        "Severity",

        "Description",

        "Status",

    )

    if column in execution_summary.columns

]

if alert_columns:

    alerts = execution_summary[
        alert_columns
    ]

    if alerts.empty:

        st.success(
            "No execution alerts.",
            icon="✅",
        )

    else:

        holdings_table(

            alerts,

            key="execution_alerts",

        )

else:

    st.info(
        "Execution alerts "
        "are unavailable."
    )

divider()

# =============================================================================
# Compliance Status
# =============================================================================

section(

    "Compliance Status",

    (
        "Workflow execution "
        "compliance."
    ),

)

if (

    "Status"

    in execution_summary.columns

):

    status = (

        execution_summary[
            "Status"
        ]

        .astype(str)

        .str.upper()

    )

    passed = int(
        (status == "PASS").sum()
    )

    failed = int(
        (status == "FAIL").sum()
    )

    warnings = int(
        (status == "WARNING").sum()
    )

    col1, col2, col3 = st.columns(3)

    with col1:

        st.metric(
            "Passed",
            passed,
        )

    with col2:

        st.metric(
            "Failed",
            failed,
        )

    with col3:

        st.metric(
            "Warnings",
            warnings,
        )

else:

    st.info(
        "Compliance report "
        "is unavailable."
    )

divider()

# =============================================================================
# Report Status
# =============================================================================

section(

    "Report Status",

    (
        "Workflow reports loaded "
        "for this dashboard."
    ),

)

status = pd.DataFrame(

    [

        {

            "Report": "Orders",

            "Rows": len(orders),

            "Status":

                "Available"

                if not orders.empty

                else "Missing",

        },

        {

            "Report": "Trade List",

            "Rows": len(trade_list),

            "Status":

                "Available"

                if not trade_list.empty

                else "Missing",

        },

        {

            "Report": "Execution Summary",

            "Rows": len(
                execution_summary,
            ),

            "Status":

                "Available"

                if not execution_summary.empty

                else "Missing",

        },

        {

            "Report": "Execution History",

            "Rows": len(
                execution_history,
            ),

            "Status":

                "Available"

                if not execution_history.empty

                else "Missing",

        },

        {

            "Report": "Rebalance Orders",

            "Rows": len(
                rebalance_orders,
            ),

            "Status":

                "Available"

                if not rebalance_orders.empty

                else "Missing",

        },

    ]

)

st.dataframe(

    status,

    use_container_width=True,

    hide_index=True,

)

divider()

# =============================================================================
# Explore Reports
# =============================================================================

section(

    "Explore Reports",

    (
        "Navigate to additional "
        "workflow reports."
    ),

)

left, right = st.columns(2)

with left:

    st.info(
        """
📊 **Dashboard**

Executive overview.
"""
    )

    st.info(
        """
💼 **Portfolio**

Portfolio summary.
"""
    )

    st.info(
        """
📈 **Daily Monitor**

Scanner activity.
"""
    )

with right:

    st.info(
        """
🛡️ **Risk**

Risk analytics.
"""
    )

    st.info(
        """
📉 **Performance**

Performance reports.
"""
    )

    st.info(
        """
📥 **Downloads**

Export reports.
"""
    )

divider()

# =============================================================================
# Footer
# =============================================================================

st.caption(
    "Institutional Scanner Monitor"
)

st.caption(
    "Execution Dashboard"
)

st.caption(
    (
        "Workflow Report Viewer • "
        "Institutional Trade Execution"
    )
)