"""
09_Downloads.py
===============

Institutional Downloads Center.

Provides centralized access to all reports,
exports, portfolio snapshots,
analytics outputs,
logs,
history,
and downloadable artifacts
generated by the Institutional
Scanner Monitor.

Features
--------
• Report Explorer
• Search & Filter
• Category Browser
• Bulk Downloads
• ZIP Export
• Report Metadata
• Diagnostics
• Storage Analytics
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from datetime import datetime
import mimetypes
import zipfile
import tempfile
import shutil

import pandas as pd
import streamlit as st
import plotly.express as px

from core.config import REPORTS_DIR
from core.theme import apply_theme

from ui.sidebar import render_sidebar
from ui.cards import dashboard_header
from ui.cards import summary_row
from ui.tables import holdings_table


# ==========================================================
# Configuration
# ==========================================================


@dataclass(slots=True)
class DownloadsConfig:

    page_title: str = "Downloads"

    page_icon: str = "📦"

    layout: str = "wide"

    reports_root: Path = REPORTS_DIR

    max_preview_rows: int = 20


CONFIG = DownloadsConfig()

# ==========================================================
# Page Configuration
# ==========================================================

st.set_page_config(

    page_title=CONFIG.page_title,

    page_icon=CONFIG.page_icon,

    layout=CONFIG.layout,

)

apply_theme()

render_sidebar()

dashboard_header()

st.title(
    "📦 Downloads Center"
)

st.caption(
    "Institutional repository for reports, exports, logs and generated analytics."
)

# ==========================================================
# Cached File Scanner
# ==========================================================


@st.cache_data(show_spinner=False)
def scan_reports(root: Path) -> pd.DataFrame:

    files = []

    if not root.exists():

        return pd.DataFrame()

    for file in root.rglob("*"):

        if not file.is_file():

            continue

        stat = file.stat()

        files.append(

            {

                "Name": file.name,

                "Folder": str(

                    file.parent.relative_to(root)

                ),

                "Extension": file.suffix.lower(),

                "Size (MB)": round(

                    stat.st_size

                    / 1024
                    / 1024,

                    3,

                ),

                "Modified": datetime.fromtimestamp(

                    stat.st_mtime

                ),

                "Path": file,

            }

        )

    if not files:

        return pd.DataFrame()

    return (

        pd.DataFrame(files)

        .sort_values(

            "Modified",

            ascending=False,

        )

        .reset_index(

            drop=True,

        )

    )

# ==========================================================
# Load Reports
# ==========================================================

reports = scan_reports(

    CONFIG.reports_root,

)

# ==========================================================
# Validation
# ==========================================================

if reports.empty:

    st.warning(

        "No downloadable reports were found."

    )

    st.stop()

# ==========================================================
# Executive KPIs
# ==========================================================

total_reports = len(reports)

total_size = reports["Size (MB)"].sum()

folders = reports["Folder"].nunique()

extensions = reports["Extension"].nunique()

summary_row(

    [

        (

            "Reports",

            total_reports,

            None,

        ),

        (

            "Folders",

            folders,

            None,

        ),

        (

            "File Types",

            extensions,

            None,

        ),

        (

            "Storage",

            f"{total_size:.2f} MB",

            None,

        ),

    ]

)

# ==========================================================
# Executive Summary
# ==========================================================

st.divider()

st.header(
    "Repository Summary"
)

left, right = st.columns(
    [2, 1]
)

with left:

    summary_row(

        [

            (

                "Latest File",

                reports.iloc[0]["Name"],

                None,

            ),

            (

                "Largest File",

                reports.sort_values(

                    "Size (MB)",

                    ascending=False,

                ).iloc[0]["Name"],

                None,

            ),

            (

                "Average Size",

                f"{reports['Size (MB)'].mean():.2f} MB",

                None,

            ),

            (

                "Newest Folder",

                reports.iloc[0]["Folder"],

                None,

            ),

        ]

    )

with right:

    health = 100

    if total_reports < 20:

        health -= 20

    if total_size > 500:

        health -= 10

    if extensions < 3:

        health -= 10

    if health >= 90:

        status = "EXCELLENT"

        color = "#16A34A"

    elif health >= 75:

        status = "GOOD"

        color = "#65A30D"

    elif health >= 60:

        status = "AVERAGE"

        color = "#F59E0B"

    else:

        status = "POOR"

        color = "#DC2626"

    st.markdown(

        f"""
<div style="
background:{color};
padding:24px;
border-radius:14px;
text-align:center;
color:white;
">

<h3>

Repository Health

</h3>

<h1>

{status}

</h1>

<h2>

{health}

</h2>

</div>
""",

        unsafe_allow_html=True,

    )

# ==========================================================
# Search & Filters
# ==========================================================

st.divider()

st.header(
    "Report Explorer"
)

left, center, right = st.columns(
    [2, 1, 1]
)

with left:

    search = st.text_input(

        "Search Files",

        placeholder="Search by filename...",

    )

with center:

    folder_filter = st.selectbox(

        "Folder",

        ["All"]

        + sorted(

            reports["Folder"]

            .unique()

            .tolist()

        ),

    )

with right:

    extension_filter = st.selectbox(

        "Extension",

        ["All"]

        + sorted(

            reports["Extension"]

            .unique()

            .tolist()

        ),

    )

filtered = reports.copy()

if search:

    filtered = filtered.loc[

        filtered["Name"]

        .str.contains(

            search,

            case=False,

            na=False,

        )

    ]

if folder_filter != "All":

    filtered = filtered.loc[

        filtered["Folder"]

        == folder_filter

    ]

if extension_filter != "All":

    filtered = filtered.loc[

        filtered["Extension"]

        == extension_filter

    ]

st.caption(

    f"{len(filtered)} file(s) found."

)

holdings_table(

    filtered.drop(

        columns=["Path"],

        errors="ignore",

    )

)

# ==========================================================
# Repository Distribution
# ==========================================================

st.divider()

st.header(
    "Repository Distribution"
)

left, right = st.columns(
    2
)

with left:

    folder_summary = (

        filtered

        .groupby(

            "Folder"

        )

        .agg(

            Files=(

                "Name",

                "count",

            ),

            Storage=(

                "Size (MB)",

                "sum",

            ),

        )

        .reset_index()

        .sort_values(

            "Files",

            ascending=False,

        )

    )

    holdings_table(

        folder_summary,

    )

with right:

    if not folder_summary.empty:

        fig = px.treemap(

            folder_summary,

            path=[

                "Folder",

            ],

            values="Storage",

            color="Files",

        )

        fig.update_layout(

            height=450,

        )

        st.plotly_chart(

            fig,

            use_container_width=True,

        )

# ==========================================================
# File Type Distribution
# ==========================================================

st.divider()

st.header(
    "File Type Analytics"
)

left, right = st.columns(
    2
)

extension_summary = (

    filtered

    .groupby(

        "Extension"

    )

    .agg(

        Files=(

            "Name",

            "count",

        ),

        Storage=(

            "Size (MB)",

            "sum",

        ),

    )

    .reset_index()

    .sort_values(

        "Files",

        ascending=False,

    )

)

with left:

    holdings_table(

        extension_summary,

    )

with right:

    if not extension_summary.empty:

        fig = px.pie(

            extension_summary,

            names="Extension",

            values="Files",

        )

        fig.update_layout(

            height=430,

        )

        st.plotly_chart(

            fig,

            use_container_width=True,

        )

# ==========================================================
# Storage Analytics
# ==========================================================

st.divider()

st.header(
    "Storage Analytics"
)

left, right = st.columns(
    2
)

with left:

    fig = px.histogram(

        filtered,

        x="Size (MB)",

        nbins=25,

    )

    fig.update_layout(

        height=420,

        xaxis_title="File Size (MB)",

    )

    st.plotly_chart(

        fig,

        use_container_width=True,

    )

with right:

    largest_files = (

        filtered

        .sort_values(

            "Size (MB)",

            ascending=False,

        )

        .head(15)

    )

    fig = px.bar(

        largest_files,

        x="Size (MB)",

        y="Name",

        orientation="h",

        color="Size (MB)",

        text="Size (MB)",

    )

    fig.update_layout(

        height=420,

        yaxis_title="",

        coloraxis_showscale=False,

    )

    st.plotly_chart(

        fig,

        use_container_width=True,

    )

# ==========================================================
# Recently Generated Reports
# ==========================================================

st.divider()

st.header(
    "Recently Generated Reports"
)

recent = (

    filtered

    .sort_values(

        "Modified",

        ascending=False,

    )

    .head(20)

)

holdings_table(

    recent.drop(

        columns=[

            "Path",

        ],

        errors="ignore",

    )

)

# ==========================================================
# Preview Selected Report
# ==========================================================

st.divider()

st.header(
    "Report Preview"
)

selected = st.selectbox(

    "Select Report",

    filtered["Name"],

)

selected_row = filtered.loc[

    filtered["Name"]

    == selected

].iloc[0]

selected_path = selected_row["Path"]

suffix = selected_path.suffix.lower()

st.markdown(
    f"**Folder:** `{selected_row['Folder']}`"
)

st.markdown(
    f"**Modified:** `{selected_row['Modified']}`"
)

st.markdown(
    f"**Size:** `{selected_row['Size (MB)']:.3f} MB`"
)

if suffix == ".csv":

    try:

        preview = pd.read_csv(

            selected_path,

            nrows=CONFIG.max_preview_rows,

        )

        holdings_table(

            preview,

        )

    except Exception as exc:

        st.error(

            f"Unable to preview CSV: {exc}"

        )

elif suffix in [

    ".xlsx",

    ".xls",

]:

    try:

        preview = pd.read_excel(

            selected_path,

            nrows=CONFIG.max_preview_rows,

        )

        holdings_table(

            preview,

        )

    except Exception as exc:

        st.error(

            f"Unable to preview Excel file: {exc}"

        )

else:

    mime = (

        mimetypes.guess_type(

            str(selected_path)

        )[0]

        or

        "application/octet-stream"

    )

    st.info(

        f"No preview available for {suffix} files."

    )

    with open(

        selected_path,

        "rb",

    ) as file:

        st.download_button(

            "Download Selected File",

            data=file,

            file_name=selected_path.name,

            mime=mime,

            use_container_width=True,

        )

# ==========================================================
# Individual Downloads
# ==========================================================

st.divider()

st.header(
    "Individual Downloads",
)

download_df = filtered.copy()

for _, row in download_df.iterrows():

    with st.container(border=True):

        left, center, right = st.columns(
            [5, 2, 1]
        )

        with left:

            st.markdown(
                f"### {row['Name']}"
            )

            st.caption(
                row["Folder"]
            )

            st.write(
                f"**Type:** {row['Extension']}  |  "
                f"**Size:** {row['Size (MB)']:.3f} MB"
            )

            st.write(
                f"Modified: {row['Modified']}"
            )

        with center:

            mime = (

                mimetypes.guess_type(

                    str(row["Path"])

                )[0]

                or

                "application/octet-stream"

            )

            with open(

                row["Path"],

                "rb",

            ) as file:

                st.download_button(

                    label="Download",

                    data=file,

                    file_name=row["Name"],

                    mime=mime,

                    use_container_width=True,

                    key=f"download_{row['Name']}",

                )

        with right:

            st.metric(

                "MB",

                f"{row['Size (MB)']:.2f}",

            )

# ==========================================================
# Bulk Download Builder
# ==========================================================

st.divider()

st.header(
    "Bulk Download Builder",
)

bulk_selection = st.multiselect(

    "Select Reports",

    options=filtered["Name"].tolist(),

    default=[],

)

selected_reports = filtered.loc[

    filtered["Name"]

    .isin(

        bulk_selection

    )

]

summary_row(

    [

        (

            "Selected Files",

            len(selected_reports),

            None,

        ),

        (

            "Selected Size",

            f"{selected_reports['Size (MB)'].sum():.2f} MB",

            None,

        ),

        (

            "Remaining",

            len(filtered)

            -

            len(selected_reports),

            None,

        ),

        (

            "Repository",

            len(filtered),

            None,

        ),

    ]

)

# ==========================================================
# ZIP Package Creator
# ==========================================================

st.divider()

st.header(
    "ZIP Package",
)

if selected_reports.empty:

    st.info(

        "Select one or more reports to create a ZIP archive."

    )

else:

    if st.button(

        "Create ZIP Package",

        use_container_width=True,

    ):

        temp_dir = tempfile.mkdtemp()

        zip_path = (

            Path(temp_dir)

            /

            "Institutional_Reports.zip"

        )

        with zipfile.ZipFile(

            zip_path,

            "w",

            compression=zipfile.ZIP_DEFLATED,

        ) as archive:

            for _, report in selected_reports.iterrows():

                archive.write(

                    report["Path"],

                    arcname=report["Name"],

                )

        with open(

            zip_path,

            "rb",

        ) as file:

            st.download_button(

                "Download ZIP Archive",

                data=file,

                file_name="Institutional_Reports.zip",

                mime="application/zip",

                use_container_width=True,

            )

        shutil.rmtree(

            temp_dir,

            ignore_errors=True,

        )

# ==========================================================
# Repository Diagnostics
# ==========================================================

st.divider()

st.header(
    "Repository Diagnostics",
)

diagnostics = pd.DataFrame(

    [

        (

            "Total Files",

            total_reports,

        ),

        (

            "Total Storage (MB)",

            round(

                total_size,

                2,

            ),

        ),

        (

            "Folders",

            folders,

        ),

        (

            "Extensions",

            extensions,

        ),

        (

            "Average File Size",

            round(

                reports["Size (MB)"].mean(),

                3,

            ),

        ),

        (

            "Largest File",

            reports["Size (MB)"].max(),

        ),

        (

            "Smallest File",

            reports["Size (MB)"].min(),

        ),

        (

            "Median File Size",

            reports["Size (MB)"].median(),

        ),

    ],

    columns=[

        "Metric",

        "Value",

    ],

)

holdings_table(

    diagnostics,

)

# ==========================================================
# Executive Insights
# ==========================================================

st.divider()

st.header(
    "Repository Insights",
)

insights = []

if total_reports > 100:

    insights.append(
        "Large institutional repository detected."
    )

if total_size > 1024:

    insights.append(
        "Repository exceeds 1 GB of storage."
    )

if reports["Size (MB)"].max() > 100:

    insights.append(
        "Very large report files exist."
    )

if extensions > 8:

    insights.append(
        "Repository contains diverse report formats."
    )

if folders > 10:

    insights.append(
        "Reports are well categorized across multiple folders."
    )

if not insights:

    insights.append(
        "Repository health appears normal."
    )

for insight in insights:

    st.success(
        insight,
    )

# ==========================================================
# Footer
# ==========================================================

st.divider()

st.caption(
    "Institutional Scanner Monitor"
)

st.caption(
    "Downloads Center • Report Repository • Bulk Export • ZIP Packaging • Storage Analytics"
)