FINAL_COLUMNS = [
    "Rank",
    "Stock",
    "Strategy",
    "Sector",
    "Years",
    "Trades",
    "Wins",
    "Losses",
    "Win%",
    "Avg Win %",
    "Avg Loss %",
    "Profit Factor",
    "Reward Risk",
    "Expectancy",
    "Avg days",
    "Total Return %",
    "Annual Return %",
    "CAGR %",
    "Trades / Year",
    "Profit Velocity",
    "Max Drawdown %",
    "Sharpe",
    "Sortino",
    "Recovery Factor",
    "Calmar",
    "MAR",
    "Ulcer Index",
    "Omega",
    "Target #",
    "Trail #",
    "Stop #",
    "Time #",
    "Target %",
    "Trail %",
    "Stop %",
    "Time %",
    "Quality Score",
    "Risk Score",
    "Efficiency Score",
    "Reliability Score",
    "Opportunity Score",
    "Composite Score",
    "Final Institutional Score",
    "Recommendation",
]
