"""
execution_service.py
====================

Institutional Trade Execution Engine

Responsibilities
----------------
• Order Generation
• Portfolio Rebalancing
• Position Sizing
• Transaction Cost Analysis
• Slippage Modeling
• Liquidity Validation
• Execution Constraints
• Order Simulation
• Execution Statistics
• Broker Integration (Future)

This module is intentionally independent from Streamlit and UI.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from zoneinfo import ZoneInfo
from typing import Any

import logging
import math
import uuid

import numpy as np
import pandas as pd

from .portfolio_manager import PortfolioResult
from .risk_manager import RiskResult

logger = logging.getLogger(__name__)


# =============================================================================
# Configuration
# =============================================================================


@dataclass(frozen=True)
class ExecutionConfig:
    """
    Institutional execution settings.
    """

    # ---------------------------------------------------------
    # Costs
    # ---------------------------------------------------------

    brokerage_rate: float = 0.00030

    exchange_fee: float = 0.00005

    taxes: float = 0.00020

    slippage: float = 0.00050

    # ---------------------------------------------------------
    # Order Limits
    # ---------------------------------------------------------

    max_order_value: float = 5_000_000

    max_order_quantity: int = 500_000

    min_order_quantity: int = 1

    round_lot: int = 1

    # ---------------------------------------------------------
    # Portfolio
    # ---------------------------------------------------------

    initial_capital: float = 10_000_000

    currency: str = "INR"

    allow_fractional: bool = False

    # ==========================================================
    # Risk Enforcement
    # ==========================================================

    strict_risk_enforcement: bool = False

    # ---------------------------------------------------------
    # Execution
    # ---------------------------------------------------------

    execution_algorithm: str = "VWAP"

    participation_rate: float = 0.10

    simulate_execution: bool = True


# =============================================================================
# Order Model
# =============================================================================


@dataclass
class ExecutionOrder:

    order_id: str

    ticker: str

    side: str

    quantity: int

    target_weight: float

    current_weight: float

    execution_price: float

    estimated_value: float

    estimated_cost: float

    slippage_cost: float

    status: str = "NEW"

    timestamp: datetime = field(
        default_factory=datetime.utcnow,
    )


# =============================================================================
# Statistics
# =============================================================================


@dataclass
class ExecutionStatistics:

    total_orders: int = 0

    buy_orders: int = 0

    sell_orders: int = 0

    turnover: float = 0.0

    estimated_cost: float = 0.0

    slippage_cost: float = 0.0

    total_execution_value: float = 0.0


# =============================================================================
# Result
# =============================================================================


@dataclass
class ExecutionResult:

    portfolio: pd.DataFrame

    orders: pd.DataFrame

    statistics: ExecutionStatistics

    metadata: dict[str, Any] = field(
        default_factory=dict,
    )


# =============================================================================
# Execution Service
# =============================================================================


class ExecutionService:
    """
    Institutional order execution engine.

    Workflow
    --------

    Portfolio
        │
        ▼
    Risk Validation
        │
        ▼
    Order Generation
        │
        ▼
    Slippage
        │
        ▼
    Transaction Costs
        │
        ▼
    Execution Limits
        │
        ▼
    Final Orders
    """

    def __init__(
        self,
        config: ExecutionConfig | None = None,
    ) -> None:

        self.config = (
            config
            if config is not None
            else ExecutionConfig()
        )

        logger.info(
            "ExecutionService initialized."
        )


    # =========================================================
    # Public API
    # =========================================================

    def execute(
        self,
        portfolio: PortfolioResult,
        risk: RiskResult,
    ) -> ExecutionResult:
        """
        Execute an approved portfolio.

        Parameters
        ----------
        portfolio
            Portfolio generated by PortfolioManager.

        risk
            Risk evaluation produced by RiskManager.

        Returns
        -------
        ExecutionResult
        """

        logger.info(
            "Starting execution pipeline."
        )

        positions = portfolio.portfolio.copy()

        if positions.empty:

            logger.warning(
                "Portfolio is empty."
            )

            empty = pd.DataFrame()

            execution_status = (
                "COMPLETED_WITH_WARNINGS"
                if (
                    not risk.violations.empty
                    and not critical.empty
                    and not self.config.strict_risk_enforcement
                )
                else "SUCCESS"
            )

            return ExecutionResult(
                portfolio=positions,
                orders=orders,
                statistics=statistics,
                metadata={
                    "status": execution_status,
                    "generated_at": datetime.now(
                        ZoneInfo("Asia/Kolkata")
                    ),
                    "algorithm": self.config.execution_algorithm,
                    "currency": self.config.currency,
                },
            )

        # ---------------------------------------------------------
        # Risk Validation
        # ---------------------------------------------------------

        if not risk.violations.empty:

            critical = risk.violations.loc[
                risk.violations["severity"] == "Critical"
            ]

            logger.warning(
                "Detected %d total risk violation(s), %d critical.",
                len(risk.violations),
                len(critical),
            )

            # -----------------------------------------------------
            # Critical Risk Enforcement
            # -----------------------------------------------------

            if not critical.empty:

                message = (
                    f"Portfolio contains {len(critical)} critical "
                    "risk violation(s)."
                )

                if self.config.strict_risk_enforcement:

                    logger.error(message)

                    logger.error(
                        "\n%s",
                        critical.to_string(index=False),
                    )

                    raise RuntimeError(message)

                logger.warning(
                    "%s Continuing because strict risk "
                    "enforcement is disabled.",
                    message,
                )

                logger.warning(
                    "\n%s",
                    critical.to_string(index=False),
                )

            # -----------------------------------------------------
            # Non-Critical Violations
            # -----------------------------------------------------

            else:

                logger.info(
                    "No critical risk violations detected."
                )

                logger.info(
                    "\n%s",
                    risk.violations.to_string(index=False),
                )
                
        # ---------------------------------------------------------
        # Normalize Execution Price
        # ---------------------------------------------------------

        if "price" not in positions.columns:

            if "plan_entry" in positions.columns:

                positions["price"] = positions["plan_entry"]

            elif "limit_price" in positions.columns:

                positions["price"] = positions["limit_price"]

            elif "entry_ref" in positions.columns:

                positions["price"] = positions["entry_ref"]

            elif "last_close" in positions.columns:

                positions["price"] = positions["last_close"]

            else:

                raise ValueError(
                    "No execution price available."
                )

        # ---------------------------------------------------------
        # Validate Portfolio
        # ---------------------------------------------------------
 
        positions = self._validate_orders(
            positions,
        )

        # ---------------------------------------------------------
        # Generate Orders
        # ---------------------------------------------------------

        orders = self._generate_orders(
            positions,
        )

        # ---------------------------------------------------------
        # Apply Slippage
        # ---------------------------------------------------------

        orders = self._apply_slippage(
            orders,
        )

        # ---------------------------------------------------------
        # Transaction Costs
        # ---------------------------------------------------------

        orders = self._compute_transaction_costs(
            orders,
        )

        # ---------------------------------------------------------
        # Execution Constraints
        # ---------------------------------------------------------

        orders = self._validate_execution_limits(
            orders,
        )


        # ---------------------------------------------------------
        # Statistics
        # ---------------------------------------------------------

        statistics = self._compute_statistics(
            orders,
        )

        logger.info(
            "Execution completed "
            "(orders=%d).",
            len(orders),
        )

        return ExecutionResult(
            portfolio=positions,
            orders=orders,
            statistics=statistics,
            metadata={
                "generated_at": datetime.now(ZoneInfo("Asia/Kolkata")),
                "algorithm": self.config.execution_algorithm,
                "currency": self.config.currency,
            },
        )


    # =========================================================
    # Internal Methods
    # =========================================================

    def _validate_orders(
        self,
        portfolio: pd.DataFrame,
    ) -> pd.DataFrame:
        """
        Validate portfolio before order generation.

        Returns
        -------
        pd.DataFrame
            Validated portfolio.
        """

        if portfolio.empty:

            logger.warning(
                "Portfolio is empty."
            )

            return portfolio.copy()

        portfolio = portfolio.copy()

        # =====================================================
        # Required Columns
        # =====================================================

        required_columns = (
            "ticker",
            "weight",
            "current_weight",
            "price",
        )

        missing = [
            column
            for column in required_columns
            if column not in portfolio.columns
        ]

        if missing:

            raise ValueError(
                "Missing required columns: "
                + ", ".join(missing)
            )

        # =====================================================
        # Numeric Conversion
        # =====================================================

        numeric_columns = (
            "weight",
            "current_weight",
            "price",
        )

        for column in numeric_columns:

            portfolio[column] = pd.to_numeric(
                portfolio[column],
                errors="coerce",
            )

        # =====================================================
        # Remove Duplicate Securities
        # =====================================================

        portfolio = portfolio.drop_duplicates(
            subset="ticker",
            keep="first",
        )

        # =====================================================
        # Replace Invalid Values
        # =====================================================

        portfolio = portfolio.replace(
            [np.inf, -np.inf],
            np.nan,
        )

        portfolio = portfolio.dropna(
            subset=[
                "ticker",
                "weight",
                "price",
            ]
        )

        # =====================================================
        # Positive Prices
        # =====================================================

        portfolio = portfolio[
            portfolio["price"] > 0
        ]

        # =====================================================
        # Fill Current Weight
        # =====================================================

        portfolio["current_weight"] = (
            portfolio["current_weight"]
            .fillna(0.0)
        )

        # =====================================================
        # Normalize Target Weights
        # =====================================================

        total = portfolio["weight"].sum()

        if (
            total > 0
            and not math.isclose(
                total,
                1.0,
                rel_tol=1e-6,
            )
        ):

            logger.info(
                "Normalizing weights "
                "(sum=%.6f).",
                total,
            )

            portfolio["weight"] = (
                portfolio["weight"] / total
            )

        # =====================================================
        # Weight Difference
        # =====================================================

        portfolio["weight_change"] = (
            portfolio["weight"]
            - portfolio["current_weight"]
        )

        # =====================================================
        # Side
        # =====================================================

        portfolio["side"] = np.select(
            [
                portfolio["weight_change"] > 0,
                portfolio["weight_change"] < 0,
            ],
            [
                "BUY",
                "SELL",
            ],
            default="HOLD",
        )

        # =====================================================
        # Remove Holds
        # =====================================================

        portfolio = portfolio[
            portfolio["side"] != "HOLD"
        ]

        portfolio = portfolio.reset_index(
            drop=True,
        )

        logger.info(
            "Validated %d executable orders.",
            len(portfolio),
        )

        return portfolio
    

    def _generate_orders(
        self,
        portfolio: pd.DataFrame,
    ) -> pd.DataFrame:
        """
        Generate executable orders from portfolio weights.

        Returns
        -------
        pd.DataFrame
            Orders ready for execution.
        """

        if portfolio.empty:

            return pd.DataFrame()

        orders = portfolio.copy()

        capital = self.config.initial_capital

        # =====================================================
        # Target Capital
        # =====================================================

        orders["target_value"] = (
            orders["weight"]
            * capital
        )

        orders["current_value"] = (
            orders["current_weight"]
            * capital
        )

        # =====================================================
        # Order Value
        # =====================================================

        orders["order_value"] = (
            orders["target_value"]
            - orders["current_value"]
        )

        # =====================================================
        # Execution Price
        # =====================================================

        orders["execution_price"] = (
            orders["price"]
        )

        # =====================================================
        # Quantity
        # =====================================================

        orders["quantity"] = (
            orders["order_value"].abs()
            / orders["execution_price"]
        )

        if not self.config.allow_fractional:

            orders["quantity"] = (
                np.floor(
                    orders["quantity"]
                )
            )

        # =====================================================
        # Round Lot
        # =====================================================

        if self.config.round_lot > 1:

            orders["quantity"] = (
                (
                    orders["quantity"]
                    // self.config.round_lot
                )
                * self.config.round_lot
            )

        orders["quantity"] = (
            orders["quantity"]
            .astype(int)
        )

        # =====================================================
        # Remove Zero Quantity
        # =====================================================

        orders = orders[
            orders["quantity"] > 0
        ]

        # =====================================================
        # Order IDs
        # =====================================================

        orders["order_id"] = [
            uuid.uuid4().hex.upper()
            for _ in range(len(orders))
        ]

        # =====================================================
        # Estimated Execution Value
        # =====================================================

        orders["estimated_value"] = (
            orders["quantity"]
            * orders["execution_price"]
        )

        # =====================================================
        # Remaining Cash
        # =====================================================

        cumulative = (
            orders["estimated_value"]
            .cumsum()
        )

        orders["remaining_cash"] = (
            capital - cumulative
        )

        # =====================================================
        # Order Type
        # =====================================================

        algorithm = (
            self.config.execution_algorithm
            .upper()
        )

        if algorithm in (
            "VWAP",
            "TWAP",
        ):

            orders["order_type"] = "MARKET"

        else:

            orders["order_type"] = "LIMIT"

        # =====================================================
        # Execution Status
        # =====================================================

        orders["status"] = "NEW"

        # =====================================================
        # Timestamp
        # =====================================================

        orders["created_at"] = datetime.now(ZoneInfo("Asia/Kolkata"))

        # =====================================================
        # Column Order
        # =====================================================

        columns = [
            "order_id",
            "ticker",
            "side",
            "quantity",
            "execution_price",
            "estimated_value",
            "target_value",
            "current_value",
            "order_value",
            "remaining_cash",
            "order_type",
            "status",
            "created_at",
        ]

        remaining = [
            c
            for c in orders.columns
            if c not in columns
        ]

        orders = orders[
            columns + remaining
        ]

        logger.info(
            "Generated %d execution orders.",
            len(orders),
        )

        return orders.reset_index(
            drop=True,
        )

    

    def _apply_slippage(
        self,
        orders: pd.DataFrame,
    ) -> pd.DataFrame:
        """
        Apply execution slippage to orders.

        BUY  -> Price increases
        SELL -> Price decreases
        """

        if orders.empty:

            return orders.copy()

        orders = orders.copy()

        slippage = self.config.slippage

        # =====================================================
        # Adjust Execution Price
        # =====================================================

        buy_mask = (
            orders["side"] == "BUY"
        )

        sell_mask = (
            orders["side"] == "SELL"
        )

        orders.loc[
            buy_mask,
            "fill_price",
        ] = (
            orders.loc[
                buy_mask,
                "execution_price",
            ]
            * (1 + slippage)
        )

        orders.loc[
            sell_mask,
            "fill_price",
        ] = (
            orders.loc[
                sell_mask,
                "execution_price",
            ]
            * (1 - slippage)
        )

        # =====================================================
        # Slippage Amount
        # =====================================================

        orders["slippage_per_share"] = (
            orders["fill_price"]
            - orders["execution_price"]
        ).abs()

        orders["slippage_cost"] = (
            orders["slippage_per_share"]
            * orders["quantity"]
        )

        # =====================================================
        # Final Trade Value
        # =====================================================

        orders["executed_value"] = (
            orders["fill_price"]
            * orders["quantity"]
        )

        # =====================================================
        # Execution Quality
        # =====================================================

        orders["slippage_pct"] = (
            orders["slippage_cost"]
            / orders["estimated_value"]
        )

        orders["slippage_pct"] = (
            orders["slippage_pct"]
            .replace(
                [np.inf, -np.inf],
                0.0,
            )
            .fillna(0.0)
        )

        # =====================================================
        # Fill Status
        # =====================================================

        orders["fill_status"] = "FILLED"

        logger.info(
            "Applied slippage to %d orders.",
            len(orders),
        )

        return orders

    
    def _compute_transaction_costs(
        self,
        orders: pd.DataFrame,
    ) -> pd.DataFrame:
        """
        Compute execution transaction costs.

        Includes
        --------
        • Brokerage
        • Exchange Fees
        • Taxes
        • Total Cost
        • Net Trade Value
        """

        if orders.empty:

            return orders.copy()

        orders = orders.copy()

        # =====================================================
        # Brokerage
        # =====================================================

        orders["brokerage"] = (
            orders["executed_value"]
            * self.config.brokerage_rate
        )

        # =====================================================
        # Exchange Charges
        # =====================================================

        orders["exchange_fee"] = (
            orders["executed_value"]
            * self.config.exchange_fee
        )

        # =====================================================
        # Taxes
        # =====================================================

        orders["tax"] = (
            orders["executed_value"]
            * self.config.taxes
        )

        # =====================================================
        # Total Cost
        # =====================================================

        orders["transaction_cost"] = (
            orders["brokerage"]
            + orders["exchange_fee"]
            + orders["tax"]
            + orders["slippage_cost"]
        )

        # =====================================================
        # Net Execution Value
        # =====================================================

        buy_mask = (
            orders["side"] == "BUY"
        )

        sell_mask = (
            orders["side"] == "SELL"
        )

        orders.loc[
            buy_mask,
            "net_execution_value",
        ] = (
            orders.loc[
                buy_mask,
                "executed_value",
            ]
            + orders.loc[
                buy_mask,
                "transaction_cost",
            ]
        )

        orders.loc[
            sell_mask,
            "net_execution_value",
        ] = (
            orders.loc[
                sell_mask,
                "executed_value",
            ]
            - orders.loc[
                sell_mask,
                "transaction_cost",
            ]
        )

        # =====================================================
        # Cost Percentage
        # =====================================================

        orders["cost_pct"] = (
            orders["transaction_cost"]
            / orders["executed_value"]
        )

        orders["cost_pct"] = (
            orders["cost_pct"]
            .replace(
                [np.inf, -np.inf],
                np.nan,
            )
            .fillna(0.0)
        )

        # =====================================================
        # Cost Breakdown
        # =====================================================

        orders["total_fees"] = (
            orders["brokerage"]
            + orders["exchange_fee"]
            + orders["tax"]
        )

        # =====================================================
        # Execution Efficiency
        # =====================================================

        orders["execution_efficiency"] = (
            1.0 - orders["cost_pct"]
        )

        orders["execution_efficiency"] = (
            orders["execution_efficiency"]
            .clip(
                lower=0.0,
                upper=1.0,
            )
        )

        logger.info(
            "Computed transaction costs "
            "for %d orders.",
            len(orders),
        )

        return orders
    

    def _validate_execution_limits(
        self,
        orders: pd.DataFrame,
    ) -> pd.DataFrame:
        """
        Validate execution constraints.

        Removes invalid orders and annotates rejected ones.
        """

        if orders.empty:

            return orders.copy()

        orders = orders.copy()

        # =====================================================
        # Validation Status
        # =====================================================

        orders["validation_status"] = "VALID"

        orders["validation_reason"] = ""

        # =====================================================
        # Quantity Limits
        # =====================================================

        low_qty = (
            orders["quantity"]
            < self.config.min_order_quantity
        )

        orders.loc[
            low_qty,
            "validation_status",
        ] = "REJECTED"

        orders.loc[
            low_qty,
            "validation_reason",
        ] = "Quantity below minimum"

        high_qty = (
            orders["quantity"]
            > self.config.max_order_quantity
        )

        orders.loc[
            high_qty,
            "validation_status",
        ] = "REJECTED"

        orders.loc[
            high_qty,
            "validation_reason",
        ] = "Quantity exceeds maximum"

        # =====================================================
        # Order Value
        # =====================================================

        large_orders = (
            orders["executed_value"]
            > self.config.max_order_value
        )

        orders.loc[
            large_orders,
            "validation_status",
        ] = "REJECTED"

        orders.loc[
            large_orders,
            "validation_reason",
        ] = "Order value exceeds limit"

        # =====================================================
        # Invalid Prices
        # =====================================================

        bad_price = (
            orders["fill_price"]
            <= 0
        )

        orders.loc[
            bad_price,
            "validation_status",
        ] = "REJECTED"

        orders.loc[
            bad_price,
            "validation_reason",
        ] = "Invalid execution price"

        # =====================================================
        # Invalid Executed Value
        # =====================================================

        bad_value = (
            orders["executed_value"]
            <= 0
        )

        orders.loc[
            bad_value,
            "validation_status",
        ] = "REJECTED"

        orders.loc[
            bad_value,
            "validation_reason",
        ] = "Invalid execution value"

        # =====================================================
        # Duplicate Orders
        # =====================================================

        duplicate = (
            orders.duplicated(
                subset=["ticker", "side"],
                keep=False,
            )
        )

        orders.loc[
            duplicate,
            "validation_status",
        ] = "REJECTED"

        orders.loc[
            duplicate,
            "validation_reason",
        ] = "Duplicate order"

        # =====================================================
        # Participation Rate
        # =====================================================

        if "average_daily_volume" in orders.columns:

            participation = (
                orders["quantity"]
                / orders["average_daily_volume"]
            )

            orders["participation_rate"] = (
                participation.fillna(0)
            )

            excessive = (
                orders["participation_rate"]
                > self.config.participation_rate
            )

            orders.loc[
                excessive,
                "validation_status",
            ] = "REJECTED"

            orders.loc[
                excessive,
                "validation_reason",
            ] = (
                "Participation rate exceeded"
            )

        else:

            orders["participation_rate"] = np.nan

        # =====================================================
        # Cash Validation
        # =====================================================

        cumulative_cash = (
            orders["net_execution_value"]
            .where(
                orders["side"] == "BUY",
                0.0,
            )
            .cumsum()
        )

        insufficient = (
            cumulative_cash
            > self.config.initial_capital
        )

        orders.loc[
            insufficient,
            "validation_status",
        ] = "REJECTED"

        orders.loc[
            insufficient,
            "validation_reason",
        ] = "Insufficient capital"

        # =====================================================
        # Round Lot
        # =====================================================

        if self.config.round_lot > 1:

            invalid_lot = (
                orders["quantity"]
                % self.config.round_lot
            ) != 0

            orders.loc[
                invalid_lot,
                "validation_status",
            ] = "REJECTED"

            orders.loc[
                invalid_lot,
                "validation_reason",
            ] = "Invalid lot size"

        # =====================================================
        # Summary
        # =====================================================

        logger.info(
            "Validated execution limits. "
            "Valid=%d Rejected=%d",
            (orders["validation_status"] == "VALID").sum(),
            (orders["validation_status"] == "REJECTED").sum(),
        )

        return orders

    

    def _compute_statistics(
        self,
        orders: pd.DataFrame,
    ) -> ExecutionStatistics:
        """
        Compute execution statistics.

        Returns
        -------
        ExecutionStatistics
        """

        statistics = ExecutionStatistics()

        if orders.empty:

            return statistics

        # =====================================================
        # Basic Counts
        # =====================================================

        statistics.total_orders = int(
            len(orders)
        )

        statistics.buy_orders = int(
            (orders["side"] == "BUY").sum()
        )

        statistics.sell_orders = int(
            (orders["side"] == "SELL").sum()
        )

        # =====================================================
        # Executed Value
        # =====================================================

        statistics.total_execution_value = float(
            orders["executed_value"].sum()
        )

        # =====================================================
        # Transaction Costs
        # =====================================================

        statistics.estimated_cost = float(
            orders["transaction_cost"].sum()
        )

        statistics.slippage_cost = float(
            orders["slippage_cost"].sum()
        )

        # =====================================================
        # Portfolio Turnover
        # =====================================================

        if statistics.total_execution_value > 0:

            statistics.turnover = float(
                statistics.total_execution_value
                / self.config.initial_capital
            )

        logger.info(
            "Execution statistics computed."
        )

        return statistics