"""
Data Load
=========

Load generated reports from the Strategy Comparison Engine.
"""

from __future__ import annotations

from pathlib import Path

import streamlit as st
from services.loader import (
    clear_session,
    get_sheet,
    load_reports,
    report_summary,
    validate_output_folder,
)
from themes import apply_theme

# ============================================================
# Page Configuration
# ============================================================

st.set_page_config(
    page_title="Data Load",
    page_icon="📂",
    layout="wide",
)

apply_theme()

# ============================================================
# Constants
# ============================================================

DEFAULT_OUTPUT_FOLDER = "strategy_compare_v4/output"

PAGE_TITLE = "📂 Load Generated Reports"

PAGE_CAPTION = "Load the Excel reports generated by strategy_comparison.py"

# ============================================================
# Header
# ============================================================


def render_header() -> None:
    """
    Render page header.
    """

    st.title(PAGE_TITLE)

    st.caption(PAGE_CAPTION)

    st.divider()


# ============================================================
# Helpers
# ============================================================


def reports_loaded() -> bool:
    """
    Return report loading status.
    """

    return st.session_state.get(
        "reports_loaded",
        False,
    )


def current_output_folder() -> str:
    """
    Return the current output folder.
    """

    return st.session_state.get(
        "output_folder",
        DEFAULT_OUTPUT_FOLDER,
    )


# ============================================================
# Load Reports Section
# ============================================================


def render_load_section() -> None:
    """
    Render report loading controls.
    """

    st.subheader("Output Folder")

    folder = st.text_input(
        "Output Folder",
        value=current_output_folder(),
        help="Folder containing the generated Excel reports.",
    )

    left, right = st.columns(2)

    # --------------------------------------------------------
    # Load Reports
    # --------------------------------------------------------

    with left:
        if st.button(
            "📥 Load Reports",
            use_container_width=True,
            type="primary",
        ):
            folder_path = Path(folder)

            try:
                missing_reports = validate_output_folder(
                    folder_path,
                )

                if missing_reports:
                    st.error("The following required reports are missing:")

                    for report in missing_reports:
                        st.write(f"• {report}")

                    return

                with st.spinner("Loading reports..."):
                    load_reports(folder)

                st.success("Reports loaded successfully.")

                st.caption(f"Loaded from: {folder_path.resolve()}")

            except Exception as exc:
                st.exception(exc)

    # --------------------------------------------------------
    # Clear Session
    # --------------------------------------------------------

    with right:
        if st.button(
            "🗑 Clear Session",
            use_container_width=True,
        ):
            clear_session()

            st.success("Session cleared successfully.")

            st.rerun()

    st.divider()


# ============================================================
# Status Section
# ============================================================


def render_status() -> None:
    """
    Render report loading status.
    """

    st.subheader("Status")

    summary = report_summary()

    c1, c2 = st.columns(2)

    with c1:
        st.metric(
            "Reports Loaded",
            "Yes" if summary["Loaded"] else "No",
        )

    with c2:
        st.metric(
            "Output Folder",
            summary["Output Folder"],
        )

    st.divider()


# ============================================================
# Workbook Preview
# ============================================================


def render_workbook_preview() -> None:
    """
    Preview loaded workbooks and worksheets.
    """

    if not reports_loaded():
        return

    st.subheader("Loaded Workbooks")

    workbooks = {
        "Strategy Comparison": st.session_state.strategy_report,
        "Stock Comparison": st.session_state.stock_report,
        "Leaderboards": st.session_state.leaderboard_report,
        "Correlation": st.session_state.correlation_report,
        "Robustness": st.session_state.robustness_report,
        "Portfolio": st.session_state.portfolio_report,
        "Final Report": st.session_state.final_report,
    }

    workbook_name = st.selectbox(
        "Workbook",
        options=list(workbooks.keys()),
    )

    workbook = workbooks[workbook_name]

    sheet_name = st.selectbox(
        "Worksheet",
        options=list(workbook.keys()),
    )

    df = get_sheet(
        workbook,
        sheet_name,
    )

    if df is None or df.empty:
        st.warning("Selected worksheet is empty.")

        return

    # --------------------------------------------------------
    # Dataset Statistics
    # --------------------------------------------------------

    c1, c2, c3 = st.columns(3)

    with c1:
        st.metric(
            "Rows",
            f"{len(df):,}",
        )

    with c2:
        st.metric(
            "Columns",
            len(df.columns),
        )

    with c3:
        memory = df.memory_usage(
            deep=True,
        ).sum() / (1024 * 1024)

        st.metric(
            "Memory",
            f"{memory:.2f} MB",
        )

    st.caption(f"Workbook: **{workbook_name}**")

    st.caption(f"Worksheet: **{sheet_name}**")

    st.dataframe(
        df,
        use_container_width=True,
        hide_index=True,
        height=650,
    )


# ============================================================
# Empty State
# ============================================================


def render_empty_state() -> None:
    """
    Render instructions when reports have not been loaded.
    """

    if reports_loaded():
        return

    st.info("""
### 📂 No Reports Loaded

Load the generated reports to begin using the platform.

**Expected files**

- Strategy_Comparison.xlsx
- Stock_Comparison.xlsx
- Leaderboards.xlsx
- Correlation.xlsx
- Robustness.xlsx
- Institutional_Portfolio.xlsx
- Institutional_Strategy_Report.xlsx

**Workflow**

1. Generate reports using `strategy_comparison.py`
2. Enter the output folder path
3. Click **Load Reports**
4. Navigate through the platform pages
""")


# ============================================================
# Footer
# ============================================================


def render_footer() -> None:
    """
    Render page footer.
    """

    st.divider()

    st.caption("Institutional Strategy Comparison Platform • Data Loader")

    st.caption("Version 4.0")


# ============================================================
# Main
# ============================================================


def main() -> None:
    """
    Render Data Load page.
    """

    render_header()

    render_load_section()

    render_status()

    if reports_loaded():
        render_workbook_preview()

    else:
        render_empty_state()

    render_footer()


# ============================================================
# Entry Point
# ============================================================

if __name__ == "__main__":
    main()
else:
    main()
