"""
Data Load
=========

Load generated reports from the Strategy Comparison Engine.
"""

from __future__ import annotations

from pathlib import Path

import streamlit as st
from services.loader import (
    clear_session,
    get_sheet,
    load_reports,
    report_summary,
    validate_output_folder,
)
from themes import apply_theme

st.set_page_config(
    page_title="Strategies",
    page_icon="📈",
    layout="wide",
)
apply_theme()

st.set_page_config(
    page_title="Data Load",
    page_icon="📂",
    layout="wide",
)

st.title("📂 Load Generated Reports")

st.caption("Load the Excel reports generated by strategy_comparison.py")

st.divider()

# ----------------------------------------------------------
# Output Folder
# ----------------------------------------------------------

default_folder = "output"

folder = st.text_input(
    "Output Folder",
    value=default_folder,
)

left, right = st.columns(2)

# ----------------------------------------------------------
# Load Reports
# ----------------------------------------------------------

with left:
    if st.button(
        "📥 Load Reports",
        use_container_width=True,
    ):
        try:
            folder_path = Path(folder)

            if not validate_output_folder(folder_path):
                st.error("Required reports were not found.")

            else:
                load_reports(folder)

                st.success("Reports loaded successfully.")

        except Exception as e:
            st.exception(e)

# ----------------------------------------------------------
# Clear Session
# ----------------------------------------------------------

with right:
    if st.button(
        "🗑 Clear Session",
        use_container_width=True,
    ):
        clear_session()

        st.success("Session cleared.")

st.divider()

# ----------------------------------------------------------
# Status
# ----------------------------------------------------------

st.subheader("Status")

summary = report_summary()

c1, c2 = st.columns(2)

with c1:
    st.metric(
        "Reports Loaded",
        "Yes" if summary["Loaded"] else "No",
    )

with c2:
    st.metric(
        "Output Folder",
        summary["Output Folder"],
    )

# ----------------------------------------------------------
# Workbook Summary
# ----------------------------------------------------------

if st.session_state.get("reports_loaded", False):
    st.divider()

    st.subheader("Loaded Workbooks")

    workbooks = {
        "Strategy Comparison": st.session_state.strategy_report,
        "Stock Comparison": st.session_state.stock_report,
        "Leaderboards": st.session_state.leaderboard_report,
        "Correlation": st.session_state.correlation_report,
        "Robustness": st.session_state.robustness_report,
        "Portfolio": st.session_state.portfolio_report,
        "Final Report": st.session_state.final_report,
    }

    workbook = st.selectbox(
        "Workbook",
        list(workbooks.keys()),
    )

    sheets = list(workbooks[workbook].keys())

    sheet = st.selectbox(
        "Worksheet",
        sheets,
    )

    df = get_sheet(
        workbooks[workbook],
        sheet,
    )

    st.write(f"Rows : {len(df):,}")

    st.write(f"Columns : {len(df.columns)}")

    st.dataframe(
        df,
        use_container_width=True,
        height=600,
        hide_index=True,
    )

else:
    st.info("""
Load your generated reports to begin.

Expected files:

• Strategy_Comparison.xlsx

• Stock_Comparison.xlsx

• Leaderboards.xlsx

• Correlation.xlsx

• Robustness.xlsx

• Institutional_Portfolio.xlsx

• Institutional_Strategy_Report.xlsx
""")
