"""
=============================================================
Institutional Strategy Comparison Engine V4

Module:
    comparison/strategy_compare.py

Purpose:
    Compare all strategy outputs generated by the
    Derived Metrics Engine.

Author:
    OpenAI

=============================================================
"""

from __future__ import annotations

from pathlib import Path
import pandas as pd
import numpy as np

from typing import Dict
from typing import List
from typing import Optional

# ============================================================
# Supported Strategy Folders
# ============================================================

STRATEGY_FOLDERS = [

    "backtest_F_ATR_FT",

    "backtest_F_ATR_Tr",

    "backtest_F_Str_FT",

    "backtest_F_Str_Tr",

    "backtest_WF_ATR_FT",

    "backtest_WF_ATR_Tr",

    "backtest_WF_Str_FT",

    "backtest_WF_Str_Tr",

]

# ============================================================
# Required Institutional Metrics
# ============================================================

REQUIRED_COLUMNS = [

    "Stock",

    "Composite Score",

    "Institution Rank",

    "Recommendation",

    "Expectancy",

    "Profit Factor",

    "Reward Risk",

]

# ============================================================
# Utilities
# ============================================================

def numeric(series):

    return pd.to_numeric(

        series,

        errors="coerce"

    )


def normalize(series):

    minimum = series.min()

    maximum = series.max()

    if maximum == minimum:

        return pd.Series(

            50,

            index=series.index

        )

    return (

        (series - minimum)

        /

        (maximum - minimum)

        * 100

    )

# ============================================================
# Strategy Comparison Engine
# ============================================================

class StrategyComparisonEngine:

    """
    Institutional Strategy Comparison Engine

    Responsibilities

        Load all strategies

        Merge outputs

        Compare strategies

        Rank strategies

        Rank stocks

        Recommend

        Export
    """

    def __init__(

        self,

        root_directory

    ):

        self.root = Path(

            root_directory

        )

        self.strategy_data = {}

        self.comparison_df = pd.DataFrame()

        self.stock_ranking_df = pd.DataFrame()

        self.strategy_ranking_df = pd.DataFrame()

        self.summary_df = pd.DataFrame()


    # --------------------------------------------------------

    def discover_strategies(self):

        """
        Find strategy folders.
        """

        folders = []

        for folder in STRATEGY_FOLDERS:

            path = self.root / folder

            if path.exists():

                folders.append(path)

        self.strategy_folders = folders

        return self
    
    # --------------------------------------------------------

    def locate_output_file(

        self,

        folder

    ):

        """
        Find derived metrics workbook.
        """

        excel_files = list(

            folder.glob(

                "*Institutional*.xlsx"

            )

        )

        if excel_files:

            return excel_files[0]

        excel_files = list(

            folder.glob("*.xlsx")

        )

        if excel_files:

            return excel_files[0]

        return None
    
    # --------------------------------------------------------

    def load_strategy(

        self,

        folder

    ):

        """
        Load one strategy workbook.
        """

        file = self.locate_output_file(

            folder

        )

        if file is None:

            print(

                f"Skipping {folder.name}"

            )

            return None

        df = pd.read_excel(

            file

        )

        df["Strategy"] = folder.name

        return df
    
    # --------------------------------------------------------

    def load_all_strategies(self):

        """
        Load every strategy.
        """

        print(

            "\nLoading Strategies...\n"

        )

        for folder in self.strategy_folders:

            df = self.load_strategy(

                folder

            )

            if df is None:

                continue

            self.strategy_data[

                folder.name

            ] = df

            print(

                f"{folder.name:<25}"

                f"{len(df):>5} rows"

            )

        return self
    
    # --------------------------------------------------------

    def validate_inputs(self):

        """
        Validate required columns.
        """

        for name, df in self.strategy_data.items():

            missing = [

                col

                for col in REQUIRED_COLUMNS

                if col not in df.columns

            ]

            if missing:

                raise ValueError(

                    f"\n{name}\n"

                    f"Missing Columns:\n"

                    +

                    "\n".join(missing)

                )

        return self

    # --------------------------------------------------------

    def merge_strategies(self):

        """
        Merge every strategy into one dataframe.
        """

        print(

            "\nMerging Strategies..."

        )

        frames = []

        for strategy, df in self.strategy_data.items():

            temp = df.copy()

            temp["Strategy"] = strategy

            frames.append(

                temp

            )

        self.comparison_df = pd.concat(

            frames,

            ignore_index=True

        )

        print(

            f"Merged Rows : {len(self.comparison_df)}"

        )

        return self
    
    # --------------------------------------------------------

    def standardize_columns(self):

        """
        Convert institutional metrics to numeric.
        """

        numeric_columns = [

            "Composite Score",

            "Expectancy",

            "Profit Factor",

            "Reward Risk",

            "Edge Score",

            "Reliability Score",

            "Efficiency Score",

            "Opportunity Score",

            "Risk Score",

            "Return Score",

            "Confidence Score",

            "Institution Rank",

        ]

        for col in numeric_columns:

            if col in self.comparison_df.columns:

                self.comparison_df[col] = numeric(

                    self.comparison_df[col]

                )

        return self
    
    # --------------------------------------------------------

    def normalize_scores(self):

        """
        Normalize institutional metrics.
        """

        score_columns = [

            "Composite Score",

            "Edge Score",

            "Reliability Score",

            "Efficiency Score",

            "Opportunity Score",

            "Risk Score",

            "Return Score",

        ]

        for col in score_columns:

            if col not in self.comparison_df.columns:

                continue

            self.comparison_df[

                col + " Normalized"

            ] = normalize(

                self.comparison_df[col]

            )

        return self

    # --------------------------------------------------------

    def build_keys(self):

        """
        Create unique identifiers.
        """

        self.comparison_df[

            "Comparison ID"

        ] = (

            self.comparison_df["Stock"]

            +

            "_"

            +

            self.comparison_df["Strategy"]

        )

        return self

    # --------------------------------------------------------

    def compare_by_stock(self):

        """
        Rank every strategy inside each stock.
        """

        self.comparison_df[

            "Strategy Rank"

        ] = (

            self.comparison_df

            .groupby("Stock")[

                "Composite Score"

            ]

            .rank(

                ascending=False,

                method="dense"

            )

        )

        return self

    # --------------------------------------------------------

    def compare_stocks(self):

        """
        Global institutional ranking.
        """

        self.comparison_df[

            "Global Rank"

        ] = (

            self.comparison_df[

                "Composite Score"

            ]

            .rank(

                ascending=False,

                method="dense"

            )

        )

        return self
    
    # --------------------------------------------------------

    def best_strategy_per_stock(self):

        """
        Keep highest ranked strategy
        for every stock.
        """

        idx = (

            self.comparison_df

            .groupby("Stock")[

                "Composite Score"

            ]

            .idxmax()

        )

        self.stock_ranking_df = (

            self.comparison_df

            .loc[idx]

            .sort_values(

                "Composite Score",

                ascending=False

            )

            .reset_index(

                drop=True

            )

        )

        return self
    
    # --------------------------------------------------------

    def strategy_summary(self):

        """
        Average institutional
        performance by strategy.
        """

        self.strategy_ranking_df = (

            self.comparison_df

            .groupby(

                "Strategy",

                as_index=False

            )

            .agg(

                {

                    "Composite Score":"mean",

                    "Expectancy":"mean",

                    "Profit Factor":"mean",

                    "Reward Risk":"mean",

                    "Strategy":"count",

                }

            )

        )

        self.strategy_ranking_df = (

            self.strategy_ranking_df

            .rename(

                columns={

                    "Strategy":"Trades"

                }

            )

        )

        return self

    # --------------------------------------------------------

    def rank_strategies(self):

        """
        Rank strategies by average composite score.
        """

        self.strategy_ranking_df = (

            self.strategy_ranking_df

            .sort_values(

                "Composite Score",

                ascending=False

            )

            .reset_index(

                drop=True

            )

        )

        self.strategy_ranking_df[

            "Strategy Rank"

        ] = np.arange(

            1,

            len(self.strategy_ranking_df) + 1

        )

        return self


    # --------------------------------------------------------

    def generate_recommendations(self):

        """
        Generate institutional recommendation
        from Composite Score.
        """

        score = self.comparison_df[

            "Composite Score"

        ]

        conditions = [

            score >= 90,

            score >= 80,

            score >= 70,

            score >= 60,

            score >= 50,

        ]

        choices = [

            "Strong Buy",

            "Buy",

            "Watch",

            "Improve",

            "Avoid",

        ]

        self.comparison_df[

            "Institution Recommendation"

        ] = np.select(

            conditions,

            choices,

            default="Reject"

        )

        return self


    # --------------------------------------------------------

    def generate_summary(self):

        """
        Executive summary.
        """

        self.summary_df = pd.DataFrame(

            {

                "Metric": [

                    "Strategies",

                    "Stocks",

                    "Records",

                    "Average Composite",

                    "Highest Composite",

                    "Lowest Composite",

                ],

                "Value": [

                    self.comparison_df[

                        "Strategy"

                    ].nunique(),

                    self.comparison_df[

                        "Stock"

                    ].nunique(),

                    len(

                        self.comparison_df

                    ),

                    round(

                        self.comparison_df[

                            "Composite Score"

                        ].mean(),

                        2

                    ),

                    round(

                        self.comparison_df[

                            "Composite Score"

                        ].max(),

                        2

                    ),

                    round(

                        self.comparison_df[

                            "Composite Score"

                        ].min(),

                        2

                    ),

                ],

            }

        )

        return self


    # --------------------------------------------------------

    def diagnostics(self):

        """
        Diagnostics.
        """

        self.diagnostics_report = {

            "Rows":

                len(

                    self.comparison_df

                ),

            "Strategies":

                self.comparison_df[

                    "Strategy"

                ].nunique(),

            "Stocks":

                self.comparison_df[

                    "Stock"

                ].nunique(),

            "Top Composite":

                round(

                    self.comparison_df[

                        "Composite Score"

                    ].max(),

                    2

                ),

            "Average Composite":

                round(

                    self.comparison_df[

                        "Composite Score"

                    ].mean(),

                    2

                ),

            "Lowest Composite":

                round(

                    self.comparison_df[

                        "Composite Score"

                    ].min(),

                    2

                ),

        }

        return self


    # --------------------------------------------------------

    def top_opportunities(

        self,

        top_n=20

    ):

        """
        Highest ranked opportunities.
        """

        self.top_opportunities_df = (

            self.comparison_df

            .sort_values(

                "Composite Score",

                ascending=False

            )

            .head(

                top_n

            )

            .reset_index(

                drop=True

            )

        )

        return self


    # --------------------------------------------------------

    def recommendation_summary(self):

        """
        Recommendation counts.
        """

        self.recommendation_df = (

            self.comparison_df

            .groupby(

                "Institution Recommendation"

            )

            .size()

            .reset_index(

                name="Count"

            )

            .sort_values(

                "Count",

                ascending=False

            )

        )

        return self


    # --------------------------------------------------------

    def print_summary(self):

        """
        Console summary.
        """

        print()

        print("=" * 60)

        print("INSTITUTIONAL STRATEGY COMPARISON")

        print("=" * 60)

        for k, v in self.diagnostics_report.items():

            print(

                f"{k:<25}: {v}"

            )

        print("=" * 60)

        print()

        return self


    # --------------------------------------------------------

    def get_results(self):

        """
        Return every dataframe.
        """

        return {

            "comparison":

                self.comparison_df,

            "stock_ranking":

                self.stock_ranking_df,

            "strategy_ranking":

                self.strategy_ranking_df,

            "summary":

                self.summary_df,

            "recommendation":

                self.recommendation_df,

            "top":

                self.top_opportunities_df,

        }

    # --------------------------------------------------------

    def export_results(

        self,

        output_file="Strategy_Comparison.xlsx"

    ):

        """
        Export all comparison reports.
        """

        print(

            f"\nExporting -> {output_file}"

        )

        with pd.ExcelWriter(

            output_file,

            engine="openpyxl"

        ) as writer:

            self.comparison_df.to_excel(

                writer,

                sheet_name="Comparison",

                index=False

            )

            self.stock_ranking_df.to_excel(

                writer,

                sheet_name="Best Strategy Per Stock",

                index=False

            )

            self.strategy_ranking_df.to_excel(

                writer,

                sheet_name="Strategy Ranking",

                index=False

            )

            self.top_opportunities_df.to_excel(

                writer,

                sheet_name="Top Opportunities",

                index=False

            )

            self.recommendation_df.to_excel(

                writer,

                sheet_name="Recommendations",

                index=False

            )

            self.summary_df.to_excel(

                writer,

                sheet_name="Summary",

                index=False

            )

        print(

            "Export Completed."

        )

        return self


    # --------------------------------------------------------

    def run(self):

        """
        Execute complete comparison pipeline.
        """

        return (

            self

            .discover_strategies()

            .load_all_strategies()

            .validate_inputs()

            .merge_strategies()

            .standardize_columns()

            .normalize_scores()

            .build_keys()

            .compare_by_stock()

            .compare_stocks()

            .best_strategy_per_stock()

            .strategy_summary()

            .rank_strategies()

            .generate_recommendations()

            .generate_summary()

            .diagnostics()

            .top_opportunities()

            .recommendation_summary()

            .print_summary()

        )


# ============================================================
# Convenience Function
# ============================================================

def compare_strategies(

    root_directory,

    output_file="Strategy_Comparison.xlsx"

):

    """
    Run the complete institutional
    strategy comparison engine.
    """

    engine = (

        StrategyComparisonEngine(

            root_directory

        )

        .run()

    )

    engine.export_results(

        output_file

    )

    return engine


# ============================================================
# Command Line Execution
# ============================================================

if __name__ == "__main__":

    ROOT_DIRECTORY = "."

    OUTPUT_FILE = "Strategy_Comparison.xlsx"

    compare_strategies(

        ROOT_DIRECTORY,

        OUTPUT_FILE

    )